.eslintrc
package-lock.json
package.json
packages/form-js-viewer/README.md
packages/form-js-viewer/karma.conf.js
packages/form-js-viewer/src/core/FormCore.js
packages/form-js-viewer/src/rendering/FormRenderer.js
packages/form-js-viewer/test/.eslintrc
packages/form-js-viewer/test/TestHelper.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js/CHANGELOG.md
packages/form-js/test/.eslintrc

This makes the `changed` event in the viewer available as an API for integrators to hook into.
---
Closes https://github.com/bpmn-io/form-js/issues/16.

Document and test <changed> event

---

packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/src/rendering/FormElement.js
packages/form-js-viewer/src/rendering/fields/NoopField.js
packages/form-js-viewer/src/rendering/fields/index.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js/test/spec/form.json

Related to https://github.com/bpmn-io/form-js/issues/10.
Closes https://github.com/bpmn-io/form-js/issues/26.

Fail form creation on missing renderer

---

packages/form-js-viewer/src/rendering/fields/CheckboxRenderer.js
packages/form-js-viewer/src/rendering/fields/Label.js
packages/form-js-viewer/src/rendering/fields/NumberRenderer.js
packages/form-js-viewer/src/rendering/fields/TextfieldRenderer.js
packages/form-js-viewer/src/rendering/fields/Util.js

* adds `for` and `name` attributes
* minor refactorings
Closes #32

fix: add `for` and `name` attributes for accessibility

---

packages/form-js-viewer/src/rendering/PoweredBy.js

Powered by is displayed below the form and scrolls with the form contents.
Closes https://github.com/bpmn-io/form-js/issues/17

feat(viewer): display powered-by logo below form

---

package-lock.json
package.json
packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/karma.conf.js
packages/form-js-editor/src/rendering/FormEditor.js
packages/form-js-editor/src/rendering/FormEditorRenderer.js
packages/form-js-editor/src/rendering/PropertiesPanel.js
packages/form-js-editor/src/rendering/context/FormEditorContext.js
packages/form-js-editor/test/.eslintrc
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/karma.conf.js
packages/form-js-viewer/package-lock.json
packages/form-js-viewer/src/rendering/PoweredBy.js
packages/form-js-viewer/src/rendering/fields/CheckboxRenderer.js
packages/form-js-viewer/src/rendering/fields/NumberRenderer.js
packages/form-js-viewer/src/rendering/fields/TextfieldRenderer.js
packages/form-js-viewer/src/rendering/fields/Util.js
packages/form-js-viewer/test/.eslintrc
packages/form-js-viewer/test/TestHelper.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js/karma.conf.js
packages/form-js/test/.eslintrc
packages/form-js/test/spec/Form.spec.js
packages/form-js/test/spec/FormEditor.spec.js
tsconfig.json

Related to https://github.com/camunda/camunda-modeler/pull/2179.

Prepare Integration

---

packages/form-js-editor/src/rendering/Palette.js

Related to camunda/camunda-modeler#2198

fix(editor): disallow drop onto palette

---

packages/form-js-editor/src/rendering/PropertiesPanel.js
packages/form-js-editor/test/spec/PropertiesPanel.spec.js

Related to camunda/camunda-modeler#2199

fix(editor): set min value of 0 for min and max length in properties

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/rendering/FormEditor.js
packages/form-js-editor/src/rendering/FormEditorRenderer.js
packages/form-js-editor/src/rendering/context/FormEditorContext.js
packages/form-js-editor/test/spec/FormEditor.spec.js

* add drag and drop listeners on mount and `attach` event
* remove drag and drop listeners on unmount and `detach` event
This is an intermediate solution since there is no `attachTo` and `detach` API at the moment.
Follow-up issue: https://github.com/bpmn-io/form-js/issues/50

Fix Drag & Drop

---

packages/form-js-editor/src/rendering/PropertiesPanel.js
packages/form-js-editor/test/spec/PropertiesPanel.spec.js

Closes #52
Related to https://github.com/camunda/camunda-modeler/pull/2205.

fix(editor): pass correct props to checkbox

---

.github/workflows/POST_RELEASE.yml
packages/form-js-editor/.npmignore
packages/form-js-editor/package.json
packages/form-js-viewer/.npmignore
packages/form-js-viewer/package.json
packages/form-js/.npmignore
packages/form-js/CHANGELOG.md
packages/form-js/package.json
tasks/stages/update-demo
tasks/stages/update-examples
tasks/stages/update-website

* Adds `v0.1.0` changelog entries.
* Adds POST_RELEASE action known from our other tools

Prepare v0.1.0 release

---

packages/form-js-editor/src/core/FormEditorCore.js
packages/form-js-editor/src/index.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/src/index.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js/src/index.js
packages/form-js/test/spec/Form.spec.js
packages/form-js/test/spec/FormEditor.spec.js

Closes https://github.com/bpmn-io/form-js/issues/9.

Add exporter and schemaVersion

---

package-lock.json
package.json
packages/form-js-editor/package-lock.json
packages/form-js-editor/package.json
packages/form-js-editor/rollup.config.js
packages/form-js-editor/src/index.js
packages/form-js-editor/test/TestHelper.js
packages/form-js-viewer/package.json
packages/form-js-viewer/rollup.config.js
packages/form-js-viewer/src/index.js
packages/form-js/CHANGELOG.md
packages/form-js/package.json
packages/form-js/rollup.config.js
packages/form-js/src/editor.js
packages/form-js/src/index.js
packages/form-js/src/viewer.js
packages/form-js/test/config/karma.distro.js
packages/form-js/test/config/karma.unit.js
packages/form-js/test/distro/form-editor.js
packages/form-js/test/distro/form-viewer.js

This adds UMD viewer and editor distributions to form-js.
---
Closes https://github.com/bpmn-io/form-js/issues/66.

Add UMD distribution

---

packages/form-js-editor/src/core/FormEditorCore.js
packages/form-js-editor/src/index.js
packages/form-js-editor/src/rendering/FormEditor.js
packages/form-js-editor/src/rendering/FormEditorRenderer.js
packages/form-js-editor/src/rendering/context/FormEditorContext.js
packages/form-js-editor/src/rendering/context/SelectionContext.js
packages/form-js-editor/src/rendering/properties-panel/components/TextInput.js
packages/form-js-editor/src/rendering/properties-panel/components/Textarea.js
packages/form-js-editor/src/rendering/properties-panel/entries/ValueEntry.js
packages/form-js-editor/src/types/custom.d.ts
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/src/rendering/Form.js
packages/form-js-viewer/src/rendering/FormRenderer.js
packages/form-js-viewer/src/rendering/context/FormContext.js
tsconfig.json

This surfaced a few places where we can improve the code base.
[A few issues remain](https://github.com/bpmn-io/form-js/runs/2713020035?check_suite_focus=true#step:6:81) that honestly look like plain bugs to me.

chore: lint:types editor source

---

package-lock.json
package.json
packages/form-js-editor/karma.conf.js
packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/src/core/Modeling.js
packages/form-js-editor/src/core/cmd/AddFormFieldHandler.js
packages/form-js-editor/src/core/cmd/EditFormFieldHandler.js
packages/form-js-editor/src/core/cmd/MoveFormFieldHandler.js
packages/form-js-editor/src/core/cmd/RemoveFormFieldHandler.js
packages/form-js-editor/src/core/cmd/Util.js
packages/form-js-editor/src/core/index.js
packages/form-js-editor/src/features/editor-actions/FormEditorActions.js
packages/form-js-editor/src/features/editor-actions/index.js
packages/form-js-editor/src/features/keyboard/FormEditorKeyboardBindings.js
packages/form-js-editor/src/features/keyboard/index.js
packages/form-js-editor/src/render/Renderer.js
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/test/TestHelper.js
packages/form-js-editor/test/helper/index.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-editor/test/spec/core/Modeling.spec.js
packages/form-js-editor/test/spec/features/editor-actions/FormEditorActions.spec.js
packages/form-js-editor/test/spec/features/keyboard/FormEditorKeyboardBindings.spec.js
packages/form-js-editor/test/test.css
packages/form-js-viewer/karma.conf.js
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/render/Renderer.js
packages/form-js-viewer/test/spec/Form.spec.js

* add and use destroy API
* add command stack, editor actions and keyboard binding services
* all modeling operations are executed as commands
* add test helpers
Closes #45

Add Undo and Redo

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/disabled.json

Do Not Submit Disabled Form or Form Fields

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/text.json

Ensures embedded images do not break the form layout.
---
Related to https://github.com/bpmn-io/form-js/issues/87

fix: render images with max-width=100%

---

packages/form-js/test/spec/FormEditor.spec.js

Related to https://github.com/bpmn-io/form-js/issues/97
Depends on https://github.com/bpmn-io/form-js/pull/99

test(form-js): add <id> roundtrip test

---

package-lock.json
packages/form-js-editor/package-lock.json
packages/form-js-editor/package.json
packages/form-js/CHANGELOG.md

Add missing `min-dom` dependency

---

packages/form-js-viewer/src/render/components/Util.js
packages/form-js-viewer/test/spec/render/components/Util.spec.js

fix(viewer): sanatize href's including white space characters

---

.github/workflows/CI.yml
package-lock.json
package.json
packages/form-js-editor/src/render/components/properties-panel/entries/TextEntry.js
packages/form-js-viewer/src/render/components/Sanitizer.js
packages/form-js-viewer/src/render/components/Util.js
packages/form-js-viewer/test/spec/render/components/Util.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

I've decided for the approach "improve our existing sanitizer" as outlined https://github.com/bpmn-io/form-js/commit/46357a6e4adcadec06e0d5a791f3e3efd61c3350.
Closes https://github.com/bpmn-io/form-js/issues/107.

Improve XSS sanitizing of `Text` fields

---

packages/form-js-editor/test/spec/import/Importer.spec.js
packages/form-js-editor/test/spec/other.json
packages/form-js-viewer/test/spec/import/Importer.spec.js
packages/form-js-viewer/test/spec/other.json

chore: verify reimport

---

README.md
packages/form-js-editor/README.md
packages/form-js-viewer/README.md
packages/form-js/README.md

docs: document new usage patterns

---

packages/form-js-viewer/src/core/Validator.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/core/validation/Validator.spec.js

fix(viewer): required fields must not be empty string

---

tasks/stages/update-demo
tasks/stages/update-examples
tasks/stages/update-website

Related to https://github.com/bpmn-io/dmn-js/issues/645

ci: use strict error handling in POST_RELEASE steps

---

package.json
packages/form-js-playground/LICENSE
packages/form-js-playground/README.md
packages/form-js-playground/karma.conf.js
packages/form-js-playground/package-lock.json
packages/form-js-playground/package.json
packages/form-js-playground/src/JSONView.js
packages/form-js-playground/src/Playground.css
packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/index.js
packages/form-js-playground/test/.eslintrc
packages/form-js-playground/test/TestHelper.js
packages/form-js-playground/test/coverageBundle.js
packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-playground/test/spec/form.json
packages/form-js-playground/test/test.css
packages/form-js-playground/test/testBundle.js
tsconfig.json

Not sure if it is worth to have this as part of form-js. It is great for debugging the existing form though.

Add a basic form playground

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/render/components/properties-panel/components/TextInput.js
packages/form-js-editor/src/render/components/properties-panel/components/TextInputEntry.js
packages/form-js-editor/src/render/components/properties-panel/entries/KeyEntry.js
packages/form-js-editor/src/render/hooks/usePrevious.js
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/properties-panel/components/TextInput.spec.js
packages/form-js-editor/test/spec/properties-panel/components/Util.js
packages/form-js-viewer/assets/form-js.css

---
Closes #58
Related to https://github.com/camunda/camunda-modeler/issues/2358

feat(editor): validate key

---

packages/form-js/CHANGELOG.md

chore(CHANGELOG): update to v0.3.0

---

packages/form-js-editor/src/core/Modeling.js
packages/form-js-editor/src/core/cmd/EditFormFieldHandler.js
packages/form-js-editor/test/spec/core/Modeling.spec.js

Closes https://github.com/bpmn-io/form-js/issues/111
Related to https://github.com/camunda/camunda-modeler/issues/2330

feat(modeling): allow editing multiple properties at the same time

---

packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/test/spec/Form.spec.js

Sorry for that. 😅 
Closes #133

fix: remove event listener when calling #off

---

packages/form-js-editor/package.json
packages/form-js-viewer/package.json
packages/form-js-viewer/src/Form.js

Comments good for editor assistance. Do not remove :signal_strength:.

Do not strip JSDoc comments during type generation

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/render/components/palette/Palette.js

Make Palette, Form and Properties Panel Overflow Scroll

---

packages/form-js/CHANGELOG.md

* `FEAT`: refactor selection ([#140](https://github.com/bpmn-io/form-js/pull/140))
* `FEAT`: add selection behavior ([#140](https://github.com/bpmn-io/form-js/pull/140))
* `FEAT` add editor action to select form field ([#149](https://github.com/bpmn-io/form-js/pull/149))
* `FIX`: add missing select label to properties panel ([#148](https://github.com/bpmn-io/form-js/pull/148))
* `FIX`: fix palette overflow ([#147](https://github.com/bpmn-io/form-js/pull/147))
* `FIX`: fix type definitions for `container` option when creating form or form editor ([#145](https://github.com/bpmn-io/form-js/pull/145))

chore(CHANGELOG): update to v0.4.0

---

packages/form-js-editor/package-lock.json
packages/form-js-editor/src/render/components/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/render/components/properties-panel/components/NumberInput.js
packages/form-js-editor/src/render/components/properties-panel/components/TextInput.js
packages/form-js-editor/src/render/components/properties-panel/components/Textarea.js
packages/form-js-editor/src/render/hooks/index.js
packages/form-js-editor/src/render/hooks/useDebounce.js
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/properties-panel/components/NumberInput.spec.js
packages/form-js-editor/test/spec/properties-panel/components/NumberInputEntry.spec.js
packages/form-js-editor/test/spec/properties-panel/components/TextInput.spec.js
packages/form-js-editor/test/spec/properties-panel/components/TextInputEntry.spec.js
packages/form-js-editor/test/spec/properties-panel/components/Textarea.spec.js
packages/form-js-editor/test/spec/properties-panel/components/TextareaEntry.spec.js
packages/form-js-editor/test/spec/properties-panel/helper/index.js
packages/form-js-viewer/package-lock.json

Some internal cleanups:
* Drop use of services within components but rely on hooks instead
* Prepare for cancelable debounced functions, to be added one day, maybe (https://github.com/bpmn-io/min-dash/pull/20)

Debounce debounce

---

packages/form-js-editor/src/core/FieldFactory.js
packages/form-js-editor/src/features/modeling/Modeling.js
packages/form-js-editor/src/features/modeling/behavior/IdBehavior.js
packages/form-js-editor/src/features/modeling/behavior/KeyBehavior.js
packages/form-js-editor/src/features/modeling/behavior/index.js
packages/form-js-editor/src/features/modeling/cmd/UpdateIdClaimHandler.js
packages/form-js-editor/src/features/modeling/cmd/UpdateKeyClaimHandler.js
packages/form-js-editor/src/features/modeling/index.js
packages/form-js-editor/src/import/Importer.js
packages/form-js-editor/src/render/components/properties-panel/entries/IdEntry.js
packages/form-js-editor/src/render/components/properties-panel/entries/KeyEntry.js
packages/form-js-editor/test/spec/core/FieldFactory.spec.js
packages/form-js-editor/test/spec/features/modeling/Modeling.spec.js
packages/form-js-editor/test/spec/features/modeling/behavior/IdBehavior.spec.js
packages/form-js-editor/test/spec/features/modeling/behavior/KeyBehavior.spec.js
packages/form-js-editor/test/spec/import/Importer.spec.js
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/properties-panel/helper/index.js
packages/form-js-viewer/src/core/FormFieldRegistry.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/test/spec/core/FormFieldRegistry.spec.js
packages/form-js-viewer/test/spec/import/Importer.spec.js

* generate both unique IDs and keys
* add behavior to update ID and key claims on field edit and remove

Prevent Duplicate Keys

---

packages/form-js-editor/assets/form-js-editor.css

style(editor): update background color for select state

---

packages/form-js-editor/src/render/components/palette/icons/Form.svg
packages/form-js-editor/src/render/components/palette/icons/index.js

Closes https://github.com/bpmn-io/form-js/issues/170
----
Look and feel demo:

fix: correct form icon

---

packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js

There exist other form elements that can be used if non-radio / checkbox style interaction is desired.
---
Closes #176

Disallow toggling of `<radio />` element

---

.eslintrc
package-lock.json
package.json
packages/form-js-editor/src/render/components/properties-panel/PropertiesPanel.js

Closes https://github.com/bpmn-io/form-js/issues/55

chore: validate hooks usage

---

packages/form-js-editor/src/render/components/properties-panel/groups/ValuesGroup.js

Related to camunda/camunda-modeler#2603
Related to https://github.com/camunda/camunda-modeler/issues/2541

Prevent Properties Panel from Losing Focus

---

packages/form-js-editor/src/render/components/properties-panel/components/TextInput.js
packages/form-js-editor/test/spec/properties-panel/components/TextInput.spec.js

Validate if Validate Prop Changes

---

packages/form-js-editor/src/render/components/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/render/components/properties-panel/entries/CustomValueEntry.js
packages/form-js-editor/src/render/components/properties-panel/entries/index.js
packages/form-js-editor/src/render/components/properties-panel/groups/CustomValuesGroup.js
packages/form-js-editor/src/render/components/properties-panel/groups/index.js
packages/form-js-editor/test/spec/form.json
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js
packages/form-js-viewer/src/index.js
packages/form-js/test/spec/Form.spec.js

Allow to set custom properties

---

packages/form-js-editor/src/render/components/properties-panel/entries/ValueEntry.js
packages/form-js-editor/src/render/components/properties-panel/groups/ValuesGroup.js
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js

Don't allow duplicate values for Select and Radio fields

---

packages/form-js/CHANGELOG.md

chore(CHANGELOG): update to v0.7.0

---

packages/form-js-editor/src/FormEditor.js
packages/form-js-viewer/src/Form.js

creating typedefs and assigning to class methods
closes #159

adding jsdoc type defs to Form#on and FormEditor#on methods

---

packages/form-js/CHANGELOG.md

chore(CHANGELOG): update to v0.7.1

---

packages/form-js-editor/src/render/components/properties-panel/entries/DisabledEntry.js
packages/form-js-editor/src/render/components/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/properties-panel/groups/GeneralGroup.spec.js
packages/form-js-editor/test/spec/properties-panel/groups/ValidationGroup.spec.js

* In accordance with schema https://github.com/bpmn-io/form-js/blob/master/docs/FORM_SCHEMA.md?plain=1#L32
* In accordance with existing test cases https://github.com/bpmn-io/form-js/blob/master/packages/form-js-viewer/test/spec/core/Validator.spec.js#L24
* Fixes upstream camunda/camunda-modeler#2919

fix(ValidationGroup): serialize regex pattern as <pattern>

---

package-lock.json
package.json

Fixes a couple of issues via `npm audit fix`.
Some leftovers now, but still an improvement.
🧹

deps: fixup audit errors

---

.github/workflows/MERGE_MASTER_TO_DEVELOP.yml

We need to set secrets:
* BPMN_IO_USERNAME
* BPMN_IO_EMAIL
* SLACK_CHANNEL_ID
* SLACK_BOT_TOKEN

ci: automatically merge master to develop

---

packages/form-js-viewer/assets/form-js.css

style(taglist): fix dropdown overflow

---

packages/form-js/CHANGELOG.md

Prepare alpha release from `develop`.

chore(CHANGELOG): update to v0.8.0-alpha.0

---

package-lock.json
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/src/render/components/Util.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/test/spec/dynamic.json
packages/form-js-viewer/test/spec/import/Importer.spec.js

feat: sanitize form field value on import

---

packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js
packages/form-js/src/viewer.js

feat: provide schema variable extraction API

---

README.md

Similar to what we have in other projects.

docs: add build and run instructions

---

packages/form-js-viewer/assets/form-js.css

fix: use outlines for field focus states

---

packages/form-js-editor/src/render/components/properties-panel/entries/KeyEntry.js

fix: describe `key` property agnostically

---

.github/workflows/CI.yml

feat: add mac and windows CI checks

---

packages/form-js/CHANGELOG.md

https://github.com/bpmn-io/form-js/compare/v0.8.0-alpha.0...develop

chore(CHANGELOG): update to v0.8.0-alpha.1

---

packages/form-js-viewer/src/render/components/form-fields/Taglist.js

feat: stop taglist duplicate entries during slowdowns

---

package-lock.json
package.json

Related to https://github.com/camunda/camunda-modeler/pull/3133
Tested this pretty thoroughly by copying over the dependencies. I was not able to replicate the headers bug in the modeler integration, so this should cover the fix

deps: upgrade to `properties-panel@0.21.0`

---

packages/form-js-editor/src/features/properties-panel/entries/ValuesSourceSelectEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3215

fix(editor): ensure valueSource is undoable

---

packages/form-js-viewer/assets/form-js.css

style(viewer): inherit font family

---

packages/form-js/CHANGELOG.md

* `DEPS`: update to `diagram-js@9.0.0`
* `DEPS`: update to `eslint-plugin-bpmn-io@0.16.0`
* `DEPS`: update to `min-dom@4.0.0`
* `FIX`: align default static values ([#355](https://github.com/bpmn-io/form-js/pull/355))
---
Related to https://github.com/camunda/camunda-modeler/issues/3246

chore(CHANGELOG): update to v0.9.8

---

.github/workflows/CI.yml

Closes #391 
Makes sure we fail if codecov fails to upload reports.

ci: fail on codecov error

---

.gitignore

chore: ignore .vscode folder

---

packages/form-js/CHANGELOG.md

Makes it ready to test in Tasklist /cc @vsgoulart

chore(CHANGELOG): update to v0.10.0-alpha.2

---

packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/util/numberFieldUtil.js
packages/form-js-viewer/test/spec/render/components/form-fields/util/numberFieldUtil.spec.js

- Remove ES2020 syntax
- Fix typo

fix: remove ES2020 syntax

---

packages/form-js-viewer/src/render/components/Sanitizer.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

chore(viewer): add h6 to the available HTML tags

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-viewer/assets/form-js.css

fix: align editor and viewer spacing

---

packages/form-js-viewer/src/render/components/form-fields/Number.js

fix: set number button type to 'button'

---

packages/form-js-playground/src/components/PlaygroundRoot.css

Do not force palette scrolling.

fix(playground): do not force palette scrolling

---

packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js

fix: do not serialize standalone minus in numberField

---

packages/form-js-viewer/src/core/Validator.js
packages/form-js-viewer/test/spec/core/Validator.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3384

fix: use proper variable for increment validation

---

packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js

fix: decimal values for min/max number validation

---

packages/form-js-viewer/src/render/components/form-fields/Datetime.js
packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3383

fix: display datetime time value when disabled

---

packages/form-js-viewer/assets/form-js.css

fix: Remove important from flatpicker CSS override

---

packages/form-js-viewer/src/render/components/form-fields/parts/DropdownList.js

fix: don't collapse dropdownlist on click scroll

---

packages/form-js-editor/src/features/modeling/behavior/ValidateBehavior.js
packages/form-js-editor/src/features/modeling/behavior/index.js
packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/features/modeling/behavior/ValidateBehavior.spec.js
packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js

Related to [modeler#3379](https://github.com/camunda/camunda-modeler/issues/3379)

fix(editor): remove custom validate via behavior

---

packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-viewer/src/util/constants/ValuesSourceConstants.js

Related to https://github.com/camunda/camunda-modeler/issues/3274

fix: provide default values on static source

---

docs/FORM_SCHEMA.md

Closes #510 
* Added some recently added components and properties
* Added a link to the component reference
We can break up the example separately, but so far, I still like we showcase most capabilities in a single form.

docs: update FORM_SCHEMA.md

---

packages/form-js-editor/src/features/properties-panel/entries/NumberSerializationEntry.js
packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

chore: properties panel renames

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/render/components/form-fields/Text.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

feat(editor): disable text links

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/parts/InputAdorner.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js

fix: display `taglist` disabled state properly

---

packages/form-js-editor/assets/form-js-editor.css

fix: disable user-select on drag containers

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js

Closes #506
This ended up becoming a bit larger than just the fonts.

feat: normalized font and misc styling form-wide

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/render/EditorFormFields.js
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/src/render/components/Util.js
packages/form-js-editor/src/render/components/editor-form-fields/EditorText.js
packages/form-js-editor/src/render/components/editor-form-fields/index.js
packages/form-js-editor/src/render/index.js
packages/form-js-editor/test/TestHelper.js
packages/form-js-editor/test/helper/index.js
packages/form-js-editor/test/spec/render/components/form-fields/EditorText.spec.js
packages/form-js-editor/test/spec/render/components/form-fields/helper/index.js
packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/render/FormFields.js
packages/form-js-viewer/src/render/components/form-fields/Text.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

Properly implemented. 
Related to https://github.com/camunda/tasklist/issues/2440

feat: editor form fields extension point + migrate `Text` to it

---

package-lock.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3382

feat: provide validations for decimal digits prop

---

packages/form-js/CHANGELOG.md

chore(CHANGELOG): update to v0.12.0

---

package-lock.json
package.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/palette/components/Palette.js
packages/form-js-editor/src/features/properties-panel/PropertiesPanelHeaderProvider.js
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/src/render/components/editor-form-fields/EditorText.js
packages/form-js-integration/package.json
packages/form-js-integration/src/application.ts
packages/form-js-viewer/package.json
packages/form-js-viewer/src/render/components/icons/index.js
packages/form-js/package.json

Closes #529
* fixes missing external types
* execute type integration test
* refactor `iconsByType` to a helper function

fix(tsc): copy types flat

---

packages/form-js-editor/src/features/palette/components/Palette.js

Related to https://github.com/camunda/camunda-modeler/issues/3448

chore(palette): use correct article in title

---

package-lock.json

deps: fixup npm audit errors

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-viewer/assets/form-js.css

Reported via https://github.com/bpmn-io/form-js/pull/316#pullrequestreview-1301013304
Note the issue only appeared in Firefox.

style: correct date time input heights

---

package-lock.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/entries/InputKeyValuesSourceEntry.js

feat(editor): improve dynamic input field description

---

packages/form-js-viewer/assets/form-js-base.css

Fixed transparent input backgrounds and disabled state borders

---

docs/FORM_SCHEMA.md
packages/form-js-viewer/src/index.js
packages/form-js/test/spec/Form.spec.js

chore: update to `schemaVersion@8`

---

packages/form-js/CHANGELOG.md

Related to https://github.com/camunda/team-hto/issues/189

chore(CHANGELOG): update to v0.13.0

---

packages/form-js-editor/assets/form-js-editor-base.css

fix: made editor buttons clickthrough

---

packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js
packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/core/Validator.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/test/spec/core/Validator.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

feat: implemented `required` where it was missing

---

packages/form-js-editor/src/features/properties-panel/entries/StaticValuesSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ValueEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

fix: compare labels properly in unique validation

---

packages/form-js-viewer/src/features/expression-language/FeelExpressionLanguage.js
packages/form-js-viewer/src/features/expression-language/FeelersTemplating.js
packages/form-js-viewer/src/features/expression-language/variableExtractionHelpers.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/features/expression-language/FeelExpressionLanguage.spec.js
packages/form-js-viewer/test/spec/template-variable-complex.json
packages/form-js-viewer/test/spec/template-variable.json
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

My condolences to whoever reviews this. Send a message if you need assistance, but this is the kind of scenario where writing readable code is very challenging.

fix: getSchemaVariable accounts for feelers expressions

---

packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-viewer/src/render/components/form-fields/Text.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

Closes #116
Requires flag to be enabled for Tasklist, Web modeler, maybe Desktop modeler?

feat: added textLinkTarget property to form-viewer

---

packages/form-js-editor/src/features/properties-panel/entries/StaticValuesSourceEntry.js
packages/form-js-editor/src/features/properties-panel/groups/CustomValuesGroup.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/redundantValues.json

fix: custom properties/static values redundancy

---

packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-playground/src/components/JSONEditor.js
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-viewer/src/render/components/FormComponent.js

Fixup some a11y issues found during https://github.com/camunda/team-hto/issues/214 (form-playground).
* allow setting aria-label in each playground component

feat(playground): set aria-label for each component

---

packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js

Closes #617 
Make sure a non-searchable select's label is properly bound to an input field. This was an issue reported via https://github.com/camunda/team-hto/issues/214

Accessible select component

---

packages/form-js-viewer/assets/form-js-base.css

fix: prioritize adorner sizing

---

packages/form-js-viewer/src/render/components/Errors.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Datetime.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

feat: Correlate error messages to fields

---

packages/form-js-editor/assets/form-js-editor-base.css

Closes #623
Demo: https://demo-623-editor-viewport--camunda-form-playground.netlify.app/

style(editor): set width to drop containers

---

packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

Draft due to dependency on #620 
Closes #380

fix: sanitize textfield newlines 

---

packages/form-js-editor/src/features/palette/components/Palette.js
packages/form-js-editor/test/spec/features/palette/Palette.spec.js

fix: adjusted component lib search

---

packages/form-js-viewer/assets/form-js-base.css

fix: more gracefully handle tiny fields with adorners

---

packages/form-js-viewer/src/render/components/Sanitizer.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

fix: support markdown tables

---

package-lock.json
packages/form-js-carbon-styles/package.json

deps(carbon): mark `@carbon/elements` and `styled-components` as peer dependencies

---

packages/form-js-playground/src/components/PlaygroundRoot.js

I target master to speed things up. 
Closes #660

chore: pipe additional modules through playground

---

packages/form-js/CHANGELOG.md

@Skaiir @vsgoulart As I'm writing the third breaking change into the `v15.0.0-alpha.x` versions I'm inclined to release this as the first major alpha now. With the stuff we are going to release around additional modules next (@Skaiir), I think it deserves to be a major release 👍 
Let me know what you think!

chore(CHANGELOG): update to v1.0.0-alpha.0

---

packages/form-js-editor/src/features/SectionModuleBase.js
packages/form-js-editor/src/render/components/ModularSection.js
packages/form-js-editor/test/spec/features/palette/PaletteModule.spec.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanelModule.spec.js

Apologies for entirely circumventing the review process on this one, a fix I would have preferred not to do, but web modeller fails to render properly right now sadly, so we'll investigate this in detail later in https://github.com/bpmn-io/form-js/issues/675.

fix: circumvent section timing issues

---

package-lock.json
package.json
packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/package.json

Related to https://github.com/bpmn-io/properties-panel/issues/249
Requires https://github.com/bpmn-io/properties-panel/pull/251

adjust fx toggle variables

---

packages/form-js/CHANGELOG.md

I removed the alpha notes and condensed it into a single changelog update for the major release 🧹

chore(CHANGELOG): update to v1.0.0

---

.github/workflows/ADD_TO_HTO_PROJECT.yml

Related to https://github.com/camunda/team-hto/pull/272

ci: update ADD_TO_HTO_PROJECT action

---

packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js
packages/form-js/CHANGELOG.md

fix: getSchemaVariable for input/output variables

---

packages/form-js-viewer/assets/form-js-base.css

fix: break overflowing words in text views

---

packages/form-js-editor/src/render/components/editor-form-fields/EditorText.js
packages/form-js-editor/test/spec/render/components/form-fields/EditorText.spec.js

fix: render text placeholder for whitespace values

---

.github/workflows/VISUAL_REGRESSION.yml

chore(GHA): overwrite screenshots on master/dev

---

package-lock.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/features/properties-panel/entries/AltTextEntry.js
packages/form-js-editor/src/features/properties-panel/entries/DisabledEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ImageSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/KeyEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ReadonlyEntry.js
packages/form-js-editor/src/features/properties-panel/groups/CustomPropertiesGroup.js
packages/form-js-editor/src/features/properties-panel/groups/ValuesGroups.js
packages/form-js-editor/src/features/properties-panel/groups/index.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

Closes https://github.com/camunda/team-hto/issues/307.

feat(props): implement first set of tooltips

---

package-lock.json
package.json
packages/form-js-editor/package.json

Related to https://github.com/camunda/team-hto/issues/262
Demo available via: https://demo-popup-editor-demo--camunda-form-playground.netlify.app/
What's included
* Open up a popup editor for FEEL expressions and FEELERS templates
* Live editing in the preview
* Dragging support

Integrate Feel Popup Editor

---

packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/src/render/components/util/localisationUtil.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
packages/form-js-viewer/test/spec/render/components/util/localisationUtil.spec.js

feat: localize datepicker dates to browser

---

packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-playground/test/spec/form.json
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/util/valuesUtil.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js

fix(values): do not create empty options when valuesExpression is set

---

renovate.json

Auto-assign reviews from the team @bpmn-io/hto-dev

deps: set renovate reviewers

---

packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-playground/rollup.config.js
packages/form-js-playground/src/components/JSONEditor.js
packages/form-js-playground/src/components/PlaygroundRoot.js

Related to https://github.com/camunda/team-hto/issues/321
This adds a placeholder to the Form Input Panel.
Demo: https://demo-add-data-placeholder--camunda-form-playground.netlify.app/

Playground: JSON data placeholder

---

packages/form-js-viewer/src/render/components/index.js

export FormField

---

packages/form-js-editor/src/features/properties-panel/groups/ValuesGroups.js

chore(editor): update options tooltip

---

packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js

feat: Add tooltip when built-in phone validation is selected

---

packages/form-js-playground/test/spec/form.json
packages/form-js-viewer/src/render/components/form-fields/parts/DropdownList.js
packages/form-js-viewer/src/render/hooks/index.js
packages/form-js-viewer/src/render/hooks/useDeepCompareState.js
packages/form-js-viewer/src/render/hooks/usePrevious.js
packages/form-js-viewer/src/render/hooks/useValuesAsync.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js

Closes #809
This makes sure we re-calculate the values everytime the evaluated values from a `valuesExpression` changed.

fix(use-values): update values when evaluated values changed

---

packages/form-js/CHANGELOG.md

Related to https://github.com/camunda/team-hto/issues/351

chore(CHANGELOG): update to v1.3.0

---

package-lock.json
package.json
packages/form-js-editor/package.json
packages/form-js/CHANGELOG.md

Related to https://github.com/bpmn-io/properties-panel/pull/292

deps: update to properties-panel@3.8.0

---

packages/form-js-viewer/assets/form-js-base.css

fix: datetime resizes properly

---

README.md
packages/form-js-viewer/src/util/index.js
packages/form-js/README.md

docs: add notes about `getSchemaVariables`

---

packages/form-js-viewer/README.md
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/helper/index.js

feat: implemented <formField.search> events

---

packages/form-js-viewer/src/features/expression-language/variableExtractionHelpers.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/complex-conditions.json
packages/form-js-viewer/test/spec/features/expression-language/variableExtractionHelpers.spec.js
packages/form-js-viewer/test/spec/groups.json
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

fix: getSchemaVariables improvements

---

packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/TestHelper.js
packages/form-js-playground/test/spec/Playground.spec.js

Related to https://github.com/camunda/team-hto/issues/385

fix(playground): add `tabIndex` to json editors

---

packages/form-js-editor/src/features/modeling/FormLayoutUpdater.js
packages/form-js-editor/src/features/modeling/cmd/MoveFormFieldHandler.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-editor/test/spec/features/modeling/Modeling.spec.js
packages/form-js-editor/test/spec/form-group.json
packages/form-js-playground/test/spec/form.json

fix(moveFormField): assign new row when no row specified

---

packages/form-js-viewer/src/index.js
packages/form-js/test/spec/Form.spec.js
packages/form-json-schema/README.md
packages/form-json-schema/src/defs/columns.json
packages/form-json-schema/src/defs/component.json
packages/form-json-schema/src/defs/examples/components.json
packages/form-json-schema/src/defs/field-types/presentation-components.json
packages/form-json-schema/src/defs/rules/rules-allowed-properties.json
packages/form-json-schema/src/defs/rules/rules-required-properties.json
packages/form-json-schema/src/defs/type.json
packages/form-json-schema/src/index.json
packages/form-json-schema/test/fixtures/columns-columnsExpression-exclusive.js
packages/form-json-schema/test/fixtures/columns-not-allowed.js
packages/form-json-schema/test/fixtures/columnsExpression-not-allowed.js
packages/form-json-schema/test/fixtures/rowCount-no-number.js
packages/form-json-schema/test/fixtures/rowCount-not-allowed.js
packages/form-json-schema/test/fixtures/schemaVersion-not-supported.js
packages/form-json-schema/test/spec/validation.spec.js

chore: Bump `schemaVersion` to 13

---

packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

adjust sanitization to be more consistent across types

---

package.json
tsconfig.json

chore: Add noEmit

---

packages/form-js/README.md

This PR proposes a simple docs fix.

docs: correct component links

---

packages/form-js-editor/src/render/components/editor-form-fields/EditorIFrame.js

fix: show iframe title in editor

---

packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
packages/form-js-editor/src/features/properties-panel/entries/RepeatableEntry.js
packages/form-js-editor/src/features/properties-panel/entries/factories/simpleRangeIntegerEntryFactory.js

fix: repeatable entry parameters now validate with errors

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js

Closes #1009
Closes #1011 - This one you already approved, it seems it may have been yeeted during the big merge this morning

fix: synchronize field validation properly

---

packages/form-js-viewer/src/util/getSchemaVariables.js
packages/form-js-viewer/test/spec/html.json
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

fix: ensure html content variables are included in getSchemaVariables

---

packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js

fix: ensure simpleSelect mouseDown event deactivates normally

---

packages/form-js-viewer/src/render/components/FormField.js

fix: Prevent blur event from having value of out sync

---

packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js

fix: ensure searchable select filter is cleared with options

---

packages/form-js-editor/src/features/properties-panel/entries/DisabledEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ReadonlyEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

fix: hide readonly option when disabled is active

---

package-lock.json
packages/form-js-editor/test/spec/render/components/form-fields/helper/index.js
packages/form-js-viewer/package.json
packages/form-js-viewer/rollup.config.js
packages/form-js-viewer/src/features/markdown/MarkdownRenderer.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

chore: replace  with `showdown` with `marked`

---

packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/src/render/components/FormEditor.js

fix: display groups with no outline with a dashed outline in the editor

---

packages/form-js-viewer/src/render/components/form-fields/Table.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/dynamic-list-table-filter-interaction.json

fix: ensure dynamic list and tables interact safely

---

packages/form-js-playground/src/components/JSONEditor.js
packages/form-js-playground/test/spec/JSONEditor.spec.js

feat: do not re-instantiate JSON editors on every change

---

packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-viewer/src/render/components/index.js
packages/form-js-viewer/src/render/components/util/domUtil.js
packages/form-js-viewer/src/render/hooks/useScrollIntoView.js

fix: improve editor focus scroll

---

packages/form-js-playground/src/components/JSONEditor.js

fix: make the JSON editor readonly truly readonly

---

packages/form-js-editor/package.json
packages/form-js-playground/package.json
packages/form-js-viewer/package.json
packages/form-js/package.json

fix: properly export type definitions for typescript esm projects

---

packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/required.json

fix: prevent multiselects from validating early

---

packages/form-js-editor/src/features/properties-panel/entries/HtmlEntry.js

chore: updated html viewer documentation link

---

packages/form-js-viewer/src/render/components/form-fields/ExpressionField.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/complex-expressions.json

fix: use lodash equality in expression fields

---

packages/form-js/CHANGELOG.md

No changes to the library, simply fixing CHANGELOG formatting.

chore(CHANGELOG): correct formatting

---

package-lock.json
package.json
packages/form-js-viewer-core/index.html
packages/form-js-viewer-core/jsconfig.json
packages/form-js-viewer-core/package.json
packages/form-js-viewer-core/src/index.js
packages/form-js-viewer-core/src/jsconfig.json
packages/form-js-viewer-core/test/.eslintrc
packages/form-js-viewer-core/test/index.spec.js
packages/form-js-viewer-core/test/jsconfig.json
packages/form-js-viewer-core/vite.config.js

Based on `update-deps` until we merge that branch

chore: bootstrap viewer core

---

package-lock.json
packages/form-js-editor/package.json
packages/form-js-playground/package.json

Closes https://github.com/bpmn-io/min-dom/issues/22

fix: revert to min-dom@4.1.0

---

packages/form-js-viewer/src/util/getSchemaVariables.js
packages/form-js-viewer/test/spec/expressionField.json
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

fix: expressions are properly included in `getSchemaVariables`

---

packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/nested-complex-context.json

fix: properly build out parent context chain

---

.github/workflows/TASKLIST_CARBONISATION.yml
packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/features/properties-panel/PropertiesPanelHeaderProvider.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanelHeaderProvider.spec.js
packages/form-js-playground/test/spec/Playground.spec.js

chore: revert b80ff79

---

packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/render/components/form-fields/FilePicker.js
packages/form-js-viewer/test/spec/render/components/form-fields/FilePicker.spec.js

feat: implement basic filepicker on viewer

---

renovate.json

To save ourselves from getting a daily PR for digests.

chore: automerge digests

---

package-lock.json
packages/form-js-editor/assets/index.scss
packages/form-js-editor/package.json
packages/form-js-editor/rollup.config.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js/package.json

bump draggle

---

packages/form-js-editor/src/features/dragging/Dragging.js

fix: align drag preview/sticker properly

---

packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js

fix: adjust the am/pm time placeholder to `hh:mm --`

---

packages/form-js-editor/src/features/properties-panel/PropertiesPanelHeaderProvider.js
packages/form-js-editor/test/spec/core/FieldFactory.spec.js
packages/form-js-viewer/src/core/FieldFactory.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js

fix: do not create a simple label in datetime components

---

packages/form-js-viewer/src/render/components/form-fields/DocumentPreview.js
packages/form-js-viewer/test/spec/render/components/form-fields/DocumentPreview.spec.js

Closes https://github.com/camunda/camunda-modeler/issues/4828

fix: filter invalid data for document preview

---

packages/form-js-viewer/src/render/components/form-fields/DocumentPreview.js

Changes how we fetch PDF so it works better on stricter CSP environments
Related to https://github.com/camunda/camunda/issues/28498

fix: make PDF rendering more resilient

---

package-lock.json
package.json

deps: bump @apidevtools/json-schema-ref-parser

---

package-lock.json
package.json

chore: bump dev deps

---

package-lock.json

Lockfile was out of sync for some reason

chore: fix `package-lock.json`

---

package-lock.json
package.json
packages/form-js-editor/package.json
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/features/properties-panel/helper/index.js

fix: bump to properties-panel@3.30.2

---

packages/form-js-viewer/src/render/components/form-fields/ExpressionField.js
packages/form-js-viewer/test/spec/Form.spec.js

To test it yourself you can use this HTML file below:
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>form-js CDN Test</title>
</head>
<body>
<h1>form-js CDN Delivery Test</h1>
<div id="form"></div>
<script type="module">
import { Form } from 'https://cdn.jsdelivr.net/npm/@bpmn-io/form-js@1.16.1-alpha.0/+esm';
// Minimal schema for demonstration
const schema = {
components: [
{
label: 'Text field',
type: 'textfield',
layout: {
row: 'Row_1dwof39',
columns: null,
},
id: 'Field_0e0vj9l',
key: 'textfield_w12jhc',
},
],
type: 'default',
id: 'simple_form',
executionPlatform: 'Camunda Cloud',
executionPlatformVersion: '8.7.0',
exporter: {
name: 'Camunda Modeler',
version: '5.37.0',
}, …
```

fix: fix lodash bundling

---

packages/form-js-editor/src/features/properties-panel/groups/CustomPropertiesGroup.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

fix: use field id as an identifier for custom properties
