bpmn-io/form-js

packages/form-js-editor/src/rendering/PropertiesPanel.js
packages/form-js-viewer/src/rendering/fields/ButtonRenderer.js
packages/form-js-viewer/src/rendering/fields/CheckboxRenderer.js
packages/form-js-viewer/src/rendering/fields/DefaultRenderer.js
packages/form-js-viewer/src/rendering/fields/NumberRenderer.js
packages/form-js-viewer/src/rendering/fields/TextfieldRenderer.js
packages/form-js-viewer/src/util/index.js

Applies a number of simplifications to the properties panel.
---
**Screenshot**
---
Out of scope: `Key`, still being finalized.

Simplify editor properties

---

packages/form-js-editor/src/rendering/PropertiesPanel.js
packages/form-js-editor/test/spec/PropertiesPanel.spec.js

* textfield and number inputs now behave the same as in form-viewer
Closes #42

fix: interpret empty textfield/number as undefined

---

packages/form-js-viewer/src/core/FormCore.js

feat: improve typedefs

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/rendering/properties-panel/entries/KeyEntry.js
packages/form-js-editor/src/rendering/properties-panel/entries/TextEntry.js
packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/test/test.css

As discussed, this improves element margins in the form editor to better match the rendered form look. This is a quick fix. We'll likely ship further improvements later this quarter.

Element margins

---

README.md
packages/form-js-editor/test/TestHelper.js
packages/form-js-viewer/README.md
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/core/index.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/src/import/index.js
packages/form-js-viewer/src/index.js
packages/form-js-viewer/src/render/components/FormComponent.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Default.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/TestHelper.js
packages/form-js-viewer/test/helper/index.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/import/Importer.spec.js
packages/form-js-viewer/test/spec/rendering/components/form-fields/Checkbox.spec.js
packages/form-js-viewer/test/spec/rendering/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/rendering/components/form-fields/Radio.spec.js
packages/form-js-viewer/test/spec/rendering/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/rendering/components/form-fields/Textfield.spec.js
packages/form-js/test/distro/form-viewer.js
packages/form-js/test/spec/Form.spec.js

* add dedicated importer to viewer
* import each form field adding `id`, `parent` and `path` and adding it to form field registry
* throw error if form field of type not supported or if form field with key already exists
* call `_update` with `field` instead of `path` since `path` is now set at all times
* verify #validate is working
BREAKING CHANGES
* #createForm returns promise resolving with form instead of returning form
Closes #79
Closes #30
Follow-up issues:
* Refactor Editor Import (https://github.com/bpmn-io/form-js/issues/82)

Add Dedicated Importer to Viewer

---

packages/form-js-viewer/test/spec/Form.spec.js

This ensures our story for handling import errors works, specifically the following:
```javascript
try {
await createForm({ schema: someBrokenSchema });
} catch (error) {
// blows up on error
}
```

test: verify import error during instantiation

---

packages/form-js-editor/test/spec/form.json
packages/form-js-viewer/src/render/components/Util.js
packages/form-js-viewer/src/render/components/form-fields/Text.js
packages/form-js-viewer/test/spec/form.json
packages/form-js-viewer/test/spec/render/components/Util.spec.js

Should generate proper paragraphs from markdown now as the user would expect:
Had to workaround https://github.com/developit/preact-markup/issues/10 as well as https://github.com/developit/snarkdown/issues/75. Added a special rule to not wrap existing HTML tags (i.e. user-created `<p>` tags).
---
Related to https://github.com/bpmn-io/form-js/issues/87

fix: properly generate paragraphs

---

packages/form-js-editor/src/render/components/properties-panel/Util.js
packages/form-js-editor/test/spec/properties-panel/Util.spec.js
packages/form-js-viewer/src/render/components/form-fields/Text.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

Savely remove text without an error being thrown.
Closes #94

Do Not Error If Text Form Field Has No Text Property

---

packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/src/index.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/test/spec/Form.spec.js

Instantiating a form or form editor without the `options` argument would blow up even though we consider them optional.
```javascript
const form = new Form();
```
doesn't 💥 up anymore.

Make Options Optional

---

packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

Setting the value of a number form field from a number (e.g. `123`) to `undefined` wouldn't result in the displayed value being set to `""`. Turning the form field into a controlled component (avoiding switch between `undefined` and a value e.g. `123`) fixes the issue (cf. https://reactjs.org/docs/forms.html#controlled-components). In fact, we already did that for the `textfield` form field (cf. https://github.com/bpmn-io/form-js/blob/v0.2.4/packages/form-js-viewer/src/render/components/form-fields/Textfield.js#L19).
Closes #122

fix(viewer): turn number form field into controlled component

---

.eslintrc

closes #119
Also cf. https://github.com/bpmn-io/hour-of-code/blob/master/snippets/dmn-js_importFromSrc.md
This avoids to have something like 
```javascript
export {
createFormEditor,
FormEditor,
schemaVersion
// wrong, but works during dev:
} from '../../form-js-editor'; 
// correct:
// } from '@bpmn-io/form-js-editor'; 
```

chore(eslint): add rule to catch invalid inter-package imports

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/src/render/Renderer.js
packages/form-js-editor/src/render/components/palette/Palette.js
packages/form-js-editor/test/spec/FormEditor.spec.js

This allows users to configure a compact editor rendering mode:
In compact mode the editor is geared towards smaller screen widths, compresses the palette and potentially provides further improvements in the future.
This approach does not add true responsiveness. Instead, integrators must decide on instantiation whether the editor should be rendered compact or not. An alternative would be to provide additional APIs to trigger that behavior / make it reactive via a generic _set property_ interface (cf. https://github.com/bpmn-io/form-js/blob/22a9ac92bc45bcb309df04770fa0fc004e49a628/packages/form-js-viewer/src/Form.js#L61).

feat(editor): add compact mode

---

packages/form-js-editor/src/core/Debounce.js
packages/form-js-editor/test/spec/FormEditor.spec.js

This ensures that we debounce editor input per default, unless disabled.
This is standard behavior in editing environments and allows users to get good UX without further configuration.

feat(editor): debounce input per default

---

packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/src/import/Importer.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/test/spec/Form.spec.js

* fire <diagram.clear> and <form.clear> before import making sure the command stack is cleared
* fire <import.done> after import (necessary in the context of integrating v0.2.x into the Camunda Modeler)
* fire <diagram.destroy> to ensure diagram services like command stack are destroyed
Closes #135

fix(form-editor): clean up before import

---

packages/form-js-editor/src/render/components/properties-panel/groups/ValuesGroup.js

Get's rid of the Preact warning regarding duplicate keys.

fix(editor): assign unique keys to get rid of warning

---

packages/form-js-editor/package.json
packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/src/index.js
packages/form-js-editor/src/types.d.ts
packages/form-js-integration/package.json
packages/form-js-integration/src/application.ts
packages/form-js-viewer/package.json
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/index.js
packages/form-js-viewer/src/types.d.ts
packages/form-js/test/spec/Form.spec.js
packages/form-js/test/spec/FormEditor.spec.js
tsconfig.json

This PR externalizes our type definitions as TypeScript apparently [strips types in the weirdest of ways](https://github.com/bpmn-io/form-js/issues/142).
As part of the PR we also ensure we got more test coverage on the existing API surface we expose (https://github.com/bpmn-io/form-js/commit/4e0a2d108a27681919ea6d7d921076046b37a0af). Breaking APIs is bad, breaking APIs + type definitions is even worse.
---
Closes #142

Externalize type definitions

---

packages/form-js-editor/src/types.d.ts
packages/form-js-integration/src/application.ts
packages/form-js-viewer/src/types.d.ts

We are not able to verify this fix automatically using `form-js-integration` since we haven't enabled strict null checks at the moment. I have verified this fix manually.
Closes #144

fix: fix container type

---

packages/form-js-editor/src/render/components/properties-panel/PropertiesPanel.js

fix(editor): add missing select label

---

packages/form-js-editor/src/features/editor-actions/FormEditorActions.js
packages/form-js-editor/test/spec/features/editor-actions/FormEditorActions.spec.js

Select form fields through editor action:
```javascript
editorActions.trigger('selectFormField', { id: 'Field_1' });
```

feat(editor): add editor action to select form field

---

.github/workflows/POST_RELEASE.yml
tasks/await-published
tasks/stages/update-demo
tasks/stages/update-examples
tasks/stages/update-website

This should resolve our `POST_RELEASE` CI failures, e.g. [this one](https://github.com/bpmn-io/form-js/actions/runs/1198257674).
---
* Move `await-published` to own task (https://github.com/bpmn-io/form-js/commit/6d7a2cb71cdc1a68acab3f1b93787e47924731c5)
* Fix `await-published` to properly increment on wait
* Correct `update-example` and `update-website` hooks to work with strict error handling

Fix CI scripts

---

packages/form-js-viewer/src/render/components/Label.js
packages/form-js-viewer/test/spec/render/components/Label.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js

Prevents components wrapped in labels and the required indicator from disappearing.
Closes https://github.com/bpmn-io/form-js/issues/168
----

fix(viewer): always render label

---

packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js

Ensures tha `Number` and `Select` elements are properly reset on the UI if the form state is reset:
---
Closes https://github.com/bpmn-io/form-js/issues/155

Make `Number` and `Select` controlled components

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-viewer/assets/form-js.css

Closes #192
This replaces the existing color scheme with the new, reduced one [of the Camunda Modeler](https://github.com/camunda/camunda-modeler/issues/2459#issuecomment-951977843).
To try it out
```sh
npx @bpmn-io/sr bpmn-io/form-js#192-update-color-scheme -c 'npm run start:editor'
```
**After**
**Before**
-----
Note: I had to add one color for properties panel input box shadows on focus state. I'd propose to use this one until we add the unified form styles (cf. https://github.com/camunda/camunda-modeler/issues/2460). I'm open to discussions for finding better alternatives in the meanwhile.
```css
--color-blue-205-100-80: hsl(205, 100%, 80%);
```

Update color scheme

---

packages/form-js-editor/src/render/components/properties-panel/components/CheckboxInput.js
packages/form-js-editor/src/render/components/properties-panel/components/NumberInput.js
packages/form-js-editor/src/render/components/properties-panel/components/Select.js
packages/form-js-editor/src/render/components/properties-panel/components/Textarea.js

Instead of using the `fjs-properties-panel-textfield` class for all properties panel inputs, let's use more specific ones. That would make it easier to override certain field styles (e.g. during https://github.com/camunda/camunda-modeler/issues/2460).
We don't use `fjs-properties-panel-textfield` anywhere so far, so this change shouldn't break anything.

chore(properties-panel): use more specific selectors

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/core/Validator.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/core/Validator.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js

* if there is no empty value (number, select) empty values will be represented as `null`
---
Closes https://github.com/bpmn-io/form-js/issues/169

Represent Empty Values as Null If There Is No Empty Value

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/import/Importer.spec.js

As discussed with @marstamm, @MaxTru and @nikku we consider the current behavior to be a bug. No data should be submitted if there is no corresponding form field.
* instead of creating submitted data based on imported data and edited data submitted data is now created based on form fields
* data will be submitted for every form field that is not disabled
* no other data will be submitted
* initial data for every form field will be created during import
```javascript
const data = {
name: 'John',
surname: 'Doe'
};
const schema = {
"components": [
{
"key": "name",
"type": "textfield"
}.
{
"key": "email",
"type": "textfield"
},
{
"key": "retired",
"type": "boolean"
}
],
"type": "default"
}
const form = await createForm({
container,
data,
schema
});
const { data } = form.submit(); …
```

fix(viewer): do not submit data without corresponding field

---

packages/form-js-editor/src/render/components/properties-panel/components/SelectEntry.js
packages/form-js-editor/src/render/components/properties-panel/components/index.js
packages/form-js-editor/src/render/components/properties-panel/entries/ActionEntry.js
packages/form-js-editor/src/render/components/properties-panel/entries/DefaultValueEntry.js
packages/form-js-editor/src/render/components/properties-panel/entries/index.js
packages/form-js-editor/src/render/components/properties-panel/groups/GeneralGroup.js
packages/form-js-editor/test/spec/defaultValues.json
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/src/index.js
packages/form-js-viewer/test/spec/defaultValues.json
packages/form-js-viewer/test/spec/import/Importer.spec.js
packages/form-js/test/spec/Form.spec.js

* form fields have optional `defaultValue` property
* default value will be used during import if no value is set
* value can be changed after import
* default value can be set through properties panel
Default value is `Max Mustermann GmbH`. Resetting form resets form field to default value.
Default value can be set through properties panel.
---
Closes #191

Add Default Values to Form Fields

---

packages/form-js/CHANGELOG.md

```
* `CHORE`: update color scheme ([#193](https://github.com/bpmn-io/form-js/pull/193))
* `FEAT`: be able to set default value of a field ([#213](https://github.com/bpmn-io/form-js/pull/213)) 
* `FIX`: submit data for every field that is not disabled ([#210](https://github.com/bpmn-io/form-js/pull/210))
* `FIX`: do not submit data without corresponding field ([#210](https://github.com/bpmn-io/form-js/pull/210))
* `FIX`: prevent properties panel from losing focus ([#211](https://github.com/bpmn-io/form-js/pull/211))
* `CHORE`: properties panel inputs inherit font family ([#189](https://github.com/bpmn-io/form-js/pull/189))
* Data will now be submitted for every form field that is not disabled.
* Imported data without form field will not be submitted anymore.
```
---
Related to …

chore(CHANGELOG): update to v0.6.0

---

packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/test/spec/FormEditor.spec.js

closes #219
Fix is straight-forward, we just have to use the correct ordering when assigning export attributes so the exporter property does not get overwritten

fix(editor): override existing `exportDetails`

---

packages/form-js-viewer/src/core/Validator.js

Without `$inject`, in some configurations the minification results in invalid dependencies array.
Closes #240

fix: explicitly declare Validator deps

---

packages/form-js-playground/package.json

Just as any other package, the form-js-playground shall have a `build` task. Without, e.g. the styles won't be packaged.

chore(form-js-playground): add build script

---

package.json

In case you work in a specific library.
```sh
npm run build-watch -- @bpmn-io/form-js-editor
npm run build-watch -- @bpmn-io/form-js-viewer
npm run build-watch -- @bpmn-io/form-js-playground
```
Or to build (watch) the whole library:
```
npm run build:watch
```

chore(package): add `build:watch` script

---

packages/form-js-editor/karma.conf.js
packages/form-js-playground/karma.conf.js
packages/form-js-viewer/karma.conf.js
packages/form-js/test/config/karma.unit.js

Related to https://github.com/bpmn-io/form-js/issues/123#issuecomment-1075594064.
----
You can now generate local HTML coverage reports via 
```
COVERAGE=1 npm test
```

chore: allow local HTML coverage reports to be generated

---

packages/form-js-playground/package.json

Previously, we would publish almost all of the files in the repo:
```
❯ npm publish --dry-run --ignore-scripts
npm notice
npm notice 📦  @bpmn-io/form-js-playground@0.7.2
npm notice === Tarball Contents ===
npm notice 88B     test/.eslintrc
npm notice 1.4kB   LICENSE
npm notice 11.9kB  dist/index.cjs
npm notice 431B    src/FileDrop.css
npm notice 2.9kB   dist/assets/form-js-playground.css
npm notice 2.4kB   src/Playground.css
npm notice 100B    test/test.css
npm notice 246B    test/coverageBundle.js
npm notice 1.1MB   dist/form-playground.umd.js
npm notice 10.9kB  dist/index.es.js
npm notice 53B     src/index.js
npm notice 1.7kB   src/JSONView.js
npm notice 2.2kB   karma.conf.js
npm notice 8.9kB   src/Playground.js
npm notice 1.4kB   test/spec/Playground.spec.js
npm notice 1.0kB …
```

Use package.json#files in playground

---

package-lock.json
package.json
packages/form-js-viewer/test/helper/index.js
packages/form-js-viewer/test/spec/render/components/Label.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Button.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/parts/DropdownList.spec.js

Adds the same unit test styles as we already have in `properties-panel` and `bpmn-js-properties-panel`. I think this helps us a lot to verify that our form fields validate against basic standards.

test(viewer): add basic a11y unit tests

---

README.md
package-lock.json
package.json

Closes #300
The issue was caused by a faulty `exports` entry in the `package.json` ([Ticket](https://github.com/chaijs/chai/issues/1387)) and resolved in `4.3.5` of chai.
After upgrading, it ran as usual. For inspection what changed, look [here](https://github.com/chaijs/chai/compare/v4.3.4...v4.3.5).

Updated chai version to ^4.3.5

---

packages/form-js-editor/src/render/components/properties-panel/groups/ValuesGroups.js
packages/form-js-editor/test/spec/properties-panel/PropertiesPanel.spec.js

Closes #304
We have many internal references to "values" in variables, functions and component names. I think we can keep those to make this easier and only change the displaying values

chore: rename 'values' to 'options'

---

packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js

Related to #303
For the properties panel hint: #305 is for adding a more sophisticated solution, but for now we decided to improve the existing description:

fix(viewer): filter out invalid dynamic taglist options

---

.babelrc
package-lock.json
package.json
packages/form-js-editor/karma.conf.js
packages/form-js-editor/package.json
packages/form-js-playground/karma.conf.js
packages/form-js-viewer/karma.conf.js
packages/form-js-viewer/package.json
packages/form-js/test/config/karma.unit.js

* use babel-plugin-istanbul for coverage reporting
* fix some audit errors; the rest will be resolved once we migrate to `lerna@5` (cf. https://github.com/bpmn-io/internal-docs/issues/482)
* editor: bump `min-dom` and `min-dash`
* viewer: bump `min-dash`
-----
This suppresses a warning regarding `istanbul-instrumenter-loader`. Switching to the recommended alternative.

Housekeeping

---

packages/form-js-playground/package.json
packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/spec/Playground.spec.js

Closes #292 
---
This makes it possible to attach all playground components individually. This enables a mode for the playground to render nothing (by not providing `container` config) but only orchestrate the different instances. This is a requirement to create a product-specific playground version (cf. https://github.com/bpmn-io/internal-docs/issues/527).
This also makes the "actions" (download, embed) optional. 
**Overview components**
**Demo**
Check out [this demo](https://form-playground-demo.netlify.app/demo/) to get a feeling of what you can do with the API changes.

Flexible playground components

---

packages/form-js-editor/assets/form-js-editor.css
packages/form-js-editor/src/features/palette/components/Palette.js
packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/components/PlaygroundRoot.css
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/spec/Playground.spec.js

Closes #331 
---
This includes some adjustments required by https://github.com/camunda/form-playground/pull/1 and https://github.com/camunda/camunda-modeler/issues/3126.
* Pipe necessary FormEditor API via FormPlayground. This is needed when integrating it into the Desktop Modeler via [camunda/camunda-modeler#3126](https://github.com/camunda/camunda-modeler/issues/3126).
* `formPlayground#getEditor`
* `formPlayground#getSchema`
* `formPlayground#saveSchema`
* Emit `formPlayground.init`. This is needed to inform interested parties once the playground has been initialized. 
* Make it possible to configure `exporter` (#331) 
* Make initial schema optional
* Display palette action names in compact mode (cf. [bpmn-io/internal-docs#617 …

Form Playground adjustments

---

packages/form-js/CHANGELOG.md

This minor release includes mostly `form-js-playground` changes. As there is no schema update, we do not need to inform other product teams specifically. 
/cc @Skaiir @CatalinaMoisuc @christian-konrad

chore(CHANGELOG): update to v0.9.0

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

Closes https://github.com/bpmn-io/form-js/issues/334
* Increases the description color contrast (cf. https://dequeuniversity.com/rules/axe/4.4/color-contrast)
* Adjust a11y tests to verify it works
I'm happy to receive feedback regarding this 👍

style(viewer): increase description color contrast

---

packages/form-js-editor/assets/form-js-editor.css

Closes #337 
**Dev Environment**
- Node: v16 LTS
- Browser: Chrome 106,105; Firefox 105
- OS: Windows 11 22H2

fix(editor): scroll only palette fields

---

packages/form-js-editor/src/features/properties-panel/entries/StaticValuesSourceEntry.js

Related to https://github.com/camunda/camunda-modeler/issues/3220
This aligns the behaviour between the default value added when creating the field, and the one added when using the '+' button.

fix(editor): align default static values

---

.github/workflows/ADD_TO_HTO_PROJECT.yml

This adds a `add-to-project` action to add new `form-js` issues + prs to the [HTO project board](https://github.com/orgs/camunda/projects/41).

chore: add `ADD_TO_HTO_PROJECT` action

---

packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/components/PlaygroundRoot.css
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-viewer/src/Form.js

Closes #273 
[As discussed](https://github.com/bpmn-io/form-js/issues/273#issuecomment-1280814553), we shall always display the submit data in the output panel. We simply do a `form.submit` to rely on the exact same data, instead of using the current form state (as we do beforehand).
Demo to try it out: https://demo-submit-panel--camunda-form-playground.netlify.app/

Display correct submit data in playground output panel

---

packages/form-js/CHANGELOG.md

This only includes playground related changes, so not important for https://github.com/camunda/camunda-modeler/issues/3246. /cc @bpmn-io/modeling-dev

chore(CHANGELOG): update to v0.9.9

---

packages/form-js-editor/assets/form-js-editor.css

Closes #365
Pretty trivial fix, won't provide tests for this one as it's just not worth it

fix: allow click through taglist input in editor

---

packages/form-js-viewer/README.md

Discovered while working with @marcellobarile (cf. https://github.com/camunda/web-modeler/pull/2750). Adds a bit of documentation to the viewer docs to make it clearer how to add a priority to an event listener.

docs(viewer): document event listener priorities

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/test/spec/render/components/form-fields/Button.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js

Discovered while working on https://github.com/camunda/team-hto/issues/28. Links and submit buttons have too less contrast against a white background. I propose to increase that a bit. /cc @RomanKostka @christian-konrad 
It doesn't make a big impact visually, but a big impact a11y wise :+1: 
_Before_
_After_

fix(viewer): use blue with more contrast

---

packages/form-js-viewer/src/render/components/form-fields/Taglist.js

Related to https://github.com/camunda/team-hto/issues/28
`axe-core` doesn't throw an error because the label is relatively close to the input so screen readers might understand the connection. However, the [Carbon accessibility checker is pretty strict](https://www.ibm.com/able/requirements/requirements/#1_3_1) on that and throws an error. 💡 
/cc @RomanKostka @christian-konrad

fix(viewer): use correct input id for taglist label

---

.github/workflows/CI.yml

Firefox is currently not included: https://github.com/actions/runner-images/issues/6399.
Let's pin this for the while being.

chore(ci): pin ubuntu version

---

package-lock.json
package.json

Also adds `didi` to the editor. With this properties panel version it starts to report missing types. 
As the `viewer` also has the `didi` dependency, I wonder why the `editor` doesn't have it already.

Renovate/bpmn io properties panel 0.x

---

packages/form-js-viewer/src/index.js
packages/form-js/test/spec/Form.spec.js

Just to make sure we already did that. There will be a bunch of schema changes in the upcoming days.
Related to https://github.com/camunda/team-hto/issues/44

chore: bump to `schemaVersion@6`

---

packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/features/properties-panel/entries/ReadonlyEntry.js
packages/form-js-editor/src/features/properties-panel/entries/index.js
packages/form-js-editor/src/features/properties-panel/groups/GeneralGroup.js
packages/form-js-editor/src/features/properties-panel/groups/InteractionGroup.js
packages/form-js-editor/src/features/properties-panel/groups/index.js
packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/core/ConditionChecker.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/src/render/components/form-fields/Button.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Datetime.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/src/render/components/form-fields/parts/InputAdorner.js
packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js
packages/form-js-viewer/src/render/hooks/useCondition.js
packages/form-js-viewer/src/util/index.js

Related to #396
This includes a demo spike for the conditional properties via FEEL. It also adds the `readonly` property to showcase using FEEL expression for specific properties, and adds the capability for the `label` property as well.
_Missing for `develop`_
* clarify generic FEEL expression handling together with conditional-rendering
* label is only FEEL for demo purposes (to be removed)
* clarify readonly styling for all components (most are simply not interactible for now)
* help users is adding some validation saying that the expression should evaluate to a boolean (readonly)

Sprint week: conditional properties (read-only + label)

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/core/ConditionChecker.js
packages/form-js-viewer/src/import/Importer.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/test/spec/import/Importer.spec.js
packages/form-js-viewer/test/spec/render/components/FormField.spec.js

The main change is that we no longer have an import step for the data. We do however still have to pass it through an initialization step to apply stuff like form field value defaults and input sanitation. 
But now instead of having to specify all the values that get passed, we just pass all the values by default, and then for form fields we overwrite with defaults when it makes sense.

removed dependency on initialData

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/render/components/Label.js
packages/form-js-viewer/src/render/components/Util.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/icons/Close.svg
packages/form-js-viewer/test/spec/render/components/Util.spec.js

In order to make `form-js` more customizable we need to add these new classes. Most of this could be replaced by the [`:has()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has), but it still is behind a flag on Firefox

chore: Add extra classes so it's easier to customize components

---

package-lock.json
packages/form-js-editor/package.json

With the alpha version we started to get the following warning on Tasklist:
```
./node_modules/@bpmn-io/form-js-editor/dist/index.es.js
Module not found: Can't resolve '@bpmn-io/feel-editor' in '/home/vinicius/repos/tasklist/client/node_modules/@bpmn-io/form-js-editor/dist'
```
This is happening because `@bpmn-io/properties-panel` is not bundling `@bpmn-io/feel-editor` anymore. To fix that we're just adding `@bpmn-io/properties-panel` as a dependency

chore: add @bpmn-io/properties-panel to @bpmn-io/form-js-editor

---

packages/form-js-editor/src/features/properties-panel/entries/InputKeyValuesSourceEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

Closes #428
@RomanKostka 
Is this okay behavior? This property is required to be set always, and while I understand that preemptively erroring things in a form might be a UX problem, I think the clarity is more important to a form designer. This is a pattern we've applied for the bpmn editor as well.

feat: add `key` validation to `input values key`

---

packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/expression-external-variable.json
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

fix(get-schema-variables): add variables in text expressions

---

packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/features/properties-panel/entries/AdornerEntry.js
packages/form-js-editor/src/features/properties-panel/entries/index.js
packages/form-js-editor/src/features/properties-panel/groups/AppearanceGroup.js
packages/form-js-editor/src/features/properties-panel/groups/index.js
packages/form-js-editor/test/spec/features/properties-panel/groups/AppearanceGroup.spec.js
packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/parts/InputAdorner.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

feat: input adorners for number and text fields

---

packages/form-js-playground/src/components/PlaygroundRoot.css

Prevents visual artifacts trying to use the stock playground:

fix(playground): move modal above properties components

---

packages/form-js-playground/src/components/PlaygroundRoot.css
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/spec/Playground.spec.js

Ensures a uniform UX across our editing tools (always rendered to the right).

feat(playground): render properties panel to the right

---

packages/form-js-playground/src/components/PlaygroundRoot.js

Rename playground data panels to `Form Input` and `Form Output`:

chore(playground): adjust data panel names

---

packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js

Related to [camunda-modeler#3379](https://github.com/camunda/camunda-modeler/issues/3379)
I removed the 'custom' definition in the schema because it diverged from the previous schema versions and wasn't really required for the behavior to work. Now when you select custom the validationType property just gets cleared. 
Aside from that we switching to a non-custom schema, we now clear minLength, maxLenght, and pattern. Since we're hiding those three properties panel properties. @vsgoulart let me know if there's anything wrong you see in my approach.

fix: clear custom validation when using presets

---

packages/form-js-playground/src/components/PlaygroundRoot.css

fix(playground): props panel no longer squashes

---

packages/form-js-playground/src/components/PlaygroundRoot.css
packages/form-js-viewer/assets/form-js.css

Related to [modeler#3381](https://github.com/camunda/camunda-modeler/issues/3381)

fix: truncate adorner text

---

packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3382

fix: trim increment number value

---

packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/test/spec/FormEditor.spec.js

Closes #462
* `drag.start`
* `drag.end`
* `drag.drop`
* `drag.cancel`
* `drag.over`
* `drag.out`
Example
```js
formEditor.on('drag.start', function(event) {
const { source } = event;
source.classList.add('dragged');
});
formEditor.on('drag.drop', function(event) {
const { source } = event;
source.classList.remove('dragged');
});
```
Cf. drake events: https://github.com/bevacqua/dragula#drakeon-events

feat(editor): emit `drag` events

---

packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js
packages/form-js-viewer/test/TestHelper.js
packages/form-js-viewer/test/helper/index.js

Closes #522 
Apparently, we didn't test against the [`autocomplete-valid`](https://dequeuniversity.com/rules/axe/4.6/autocomplete-valid?application=RuleDescription) rule beforehand, as it was not part of the used test definitions. 
I added `cat.forms` to cover this; it makes anyway sense to use these best practices.

Datetime: correct `autocomplete` attribute

---

packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js

Just going to straight up disable the dates which were causing issues for now, so that we don't have the bug in the next release. We've agreed anyways that the historical use case is not a requirement for this component, fixing this is more effort than I'd like so we can take it as a future item:
Have not provided a test case as it is not really the behavior we want long term. 
Proper fix is tracked [here](https://github.com/bpmn-io/form-js/issues/533).

chore(datepicker): disable dates prior to 1900

---

packages/form-js-editor/src/features/properties-panel/groups/ValidationGroup.js
packages/form-js-editor/test/spec/features/properties-panel/groups/ValidationGroup.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3379#issuecomment-1413802106
Seems like some browsers do not work properly with `undefined` as option type. I think we should avoid this anyway.

fix(editor): use constant value for custom validation type

---

packages/form-js-viewer/assets/form-js.css
packages/form-js-viewer/src/render/components/form-fields/parts/InputAdorner.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3381

fix: text adornment ellipsis

---

packages/form-js/CHANGELOG.md

You can easily forget this. Although it is mentioned in the `README` already, I think we can be a bit more helpful in the change logs in case you need to add new style sheets.
In the future, we can consider bundling everything together (cf. #257); I am anyway currently investigating via https://github.com/camunda/team-hto/issues/133.

chore(CHANGELOG): mention `flatpickr/light.css`

---

.github/workflows/ADD_TO_HTO_PROJECT.yml
.github/workflows/DEPLOY_PLAYGROUND_PREVIEW.yml
.github/workflows/MERGE_MASTER_TO_DEVELOP.yml
.github/workflows/POST_RELEASE.yml
.github/workflows/TEARDOWN_PLAYGROUND_PREVIEW.yml

Related to https://github.com/camunda/form-playground/issues/16
This one adds two GitHub actions to create and clean up `form-playground` demos with a form-js branch attached. Some things were mirrored from [`infra-global-github-actions`](https://github.com/camunda/infra-global-github-actions/tree/main/preview-env).
- Example: [preview creation](https://github.com/bpmn-io/form-js/actions/runs/4204150254/jobs/7294433364)
- Example: [clean up](https://github.com/bpmn-io/form-js/actions/runs/4204142528/jobs/7294415851)
=> [Resulting demo](https://demo-deploy-playground-demo--camunda-form-playground.netlify.app/)
Todo:

Build and Deploy to Playground Demo (Netlify)

---

.github/workflows/DEPLOY_PLAYGROUND_PREVIEW.yml
.github/workflows/TEARDOWN_PLAYGROUND_PREVIEW.yml

Related to https://github.com/bpmn-io/form-js/pull/543#issuecomment-1438709246
Sanitizes the branch name for the preview [similar to how we do it in Tasklist.](https://github.com/camunda/tasklist/blob/master/.github/workflows/preview-env-teardown.yml#L33)

ci: sanitize branch name

---

packages/form-js-editor/src/features/properties-panel/entries/InputKeyValuesSourceEntry.js
packages/form-js-viewer/src/render/components/util/sanitizerUtil.js
packages/form-js-viewer/src/render/components/util/valuesUtil.js
packages/form-js-viewer/src/render/hooks/useValuesAsync.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/util/valuesUtil.spec.js

Closes #542 
You can now provide any mixture of input options, and without breaking the select components and output.
This is a draft PR, lacking any tests.

542 select components can consume a simple array of strings for options

---

packages/form-js-editor/src/features/properties-panel/entries/DefaultValueEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js/CHANGELOG.md

Closes #562
Also preparing the changelog so we can follow up with a patch release.

fix(editor): use proper empty value for select defaults

---

.github/workflows/POST_RELEASE.yml

We'd otherwise [generate old style lock files](https://github.com/bpmn-io/bpmn-io-demo/commit/a4d2a5edec8506498a74608fc947dc00d2f6f1af) when upgrading the demo.

ci(POST_RELEASE): use Node@16

---

packages/form-js-playground/src/components/PlaygroundRoot.css
packages/form-js-viewer/assets/form-js-base.css

We do not use the Wide grid mode (https://carbondesignsystem.com/guidelines/2x-grid/implementation#the-wide-grid), so a slight negative margin is added to both sides. We want to prevent that when embedding the viewer inside applications.
We still apply the margin to the playground to save space. 
Related to https://github.com/camunda/tasklist/pull/2746

style: properly align rows in viewer

---

packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/src/core/FormLayoutValidator.js
packages/form-js-editor/src/features/properties-panel/entries/ColumnsEntry.js
packages/form-js-editor/test/spec/core/FormLayoutValidator.form.json
packages/form-js-editor/test/spec/core/FormLayoutValidator.spec.js

Allows for uneven columns. Improves the validation to properly account for `auto` columns. It does not prevent row wrapping in every case, as we discovered via #605. I have the feeling it's rather a form-playground problem, as I can't reproduce these cases in form-js. 
Closes #605
Try it out via https://demo-605-odd-columns--camunda-form-playground.netlify.app/

feat(editor): allow uneven columns

---

.github/workflows/CI.yml

Set a retry counter to the code coverage upload. If happens in the past that the upload failed because of some random errors. Let's see whether this improves it.

ci: retry code cov upload

---

packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/test/spec/FormEditor.spec.js

Related to #173
* Make editor form fields accessible via keyboard
* Add `Enter` key handler to select focussed elements

feat(editor): make elements keyboard accessible

---

packages/form-js-editor/src/features/properties-panel/entries/DisabledEntry.js

chore(editor): move `disabled` entry to a toggle switch

---

.github/workflows/TASKLIST_CARBONISATION.yml
package-lock.json
package.json
packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/entries/DisabledEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ReadonlyEntry.js
packages/form-js-editor/test/spec/features/properties-panel/groups/GeneralGroup.spec.js
packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/src/render/hooks/index.js
packages/form-js-viewer/src/render/hooks/useReadonly.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/readonly-expression.json
packages/form-js-viewer/test/spec/render/components/FormField.spec.js
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

Closes #396 
Related to #653 
-----
Adds expression support for `readonly`.
Demo: https://demo-653-readonly-expressions--camunda-form-playground.netlify.app/

Readonly via expressions

---

packages/form-js-editor/src/features/expression-language/EditorTemplating.js
packages/form-js-editor/src/features/expression-language/index.js
packages/form-js-editor/src/features/properties-panel/entries/DescriptionEntry.js
packages/form-js-editor/src/features/properties-panel/entries/LabelEntry.js
packages/form-js-editor/test/spec/features/properties-panel/groups/GeneralGroup.spec.js
packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/render/components/Description.js
packages/form-js-viewer/src/render/components/Label.js
packages/form-js-viewer/src/render/hooks/index.js
packages/form-js-viewer/src/render/hooks/useSingleLineTemplateEvaluation.js
packages/form-js-viewer/src/render/hooks/useTemplateEvaluation.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/descriptions.json
packages/form-js-viewer/test/spec/labels.json
packages/form-js-viewer/test/spec/render/components/Description.spec.js
packages/form-js-viewer/test/spec/render/components/FormField.spec.js
packages/form-js-viewer/test/spec/render/components/Label.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checkbox.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Datetime.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Text.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textarea.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/helper/index.js
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

Related to #653 
Adds FEEL support for `label` and `description`.
Demo: https://demo-653-labels-descriptions-o--camunda-form-playground.netlify.app/

FEEL for Labels and Descriptions

---

packages/form-js-editor/src/features/properties-panel/entries/AdornerEntry.js
packages/form-js-editor/src/features/properties-panel/entries/AltTextEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ImageSourceEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/features/properties-panel/groups/AppearanceGroup.spec.js
packages/form-js-viewer/src/render/components/form-fields/Image.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/parts/TemplatedInputAdorner.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/appearance.json
packages/form-js-viewer/test/spec/images.json
packages/form-js-viewer/test/spec/render/components/form-fields/Image.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Textfield.spec.js
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

Related to #653 
Adds FEEL support for `alt`, `source` and adorners.
Demo: https://demo-653-adorners-images--camunda-form-playground.netlify.app/

FEEL for image properties and adorners

---

packages/form-js-editor/src/features/properties-panel/components/AutoFocusSelect.js
packages/form-js-editor/src/features/properties-panel/components/index.js
packages/form-js-editor/src/features/properties-panel/entries/ValuesExpressionEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ValuesSourceSelectEntry.js
packages/form-js-editor/src/features/properties-panel/entries/index.js
packages/form-js-editor/src/features/properties-panel/groups/ValuesGroups.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-viewer/src/render/hooks/useValuesAsync.js
packages/form-js-viewer/src/util/constants/ValuesSourceConstants.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/render/components/form-fields/Select.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/helper/index.js
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js
packages/form-js-viewer/test/spec/valuesExpression.json

Closes #673 
* Adds `valuesExpression` property to populate multiselect options via FEEL
* Adds `AutoFocusSelectEntry` to focus another entry after select change
Demo: https://demo-673-values-feel--camunda-form-playground.netlify.app/

Support FEEL for Multiselect Values

---

packages/form-js-carbon-styles/src/carbon-styles.js
packages/form-js-carbon-styles/test/spec/carbon-styles.spec.js
packages/form-js-viewer/assets/form-js-base.css

Fix Carbonization

---

packages/form-js-viewer/src/features/expression-language/variableExtractionHelpers.js
packages/form-js-viewer/src/util/index.js
packages/form-js-viewer/test/spec/features/expression-language/variableExtractionHelpers.spec.js
packages/form-js-viewer/test/spec/ships-example.json
packages/form-js-viewer/test/spec/util/GetSchemaVariables.spec.js

Related to https://github.com/camunda/team-hto/issues/279

fix(FEEL): vars in filters are properly parsed

---

.github/workflows/TASKLIST_CARBONISATION.yml

@pinussilvestrus I think one of the reasons the tests weren't very reliable some weeks ago is because I forgot to link changes in the Carbon custom styles

test: Fix visual regression integration linking

---

packages/form-js-viewer/assets/form-js-base.css

Closes  #684
Initially tried to approach this one programmatically, but it's not as clean as it seems, so I thought the simplest and most effective approach is to just not render the row if it has no children.

fix: hide empty rows via css

---

packages/form-js-carbon-styles/src/carbon-styles.js
packages/form-js-carbon-styles/test/spec/complex.json

Related to https://github.com/camunda/tasklist/issues/3189
Related to https://github.com/camunda/tasklist/issues/2879
----
* Making select arrow clickable
* The click handler is on the original arrow, so making it transparent so the click wents through
* Fixing wrong link styles in text views
* Docs: https://carbondesignsystem.com/components/link/usage/ (inline)

Fixing carbonization issues

---

packages/form-js-editor/src/features/properties-panel/entries/TextEntry.js

Related to https://github.com/camunda/web-modeler/issues/5483
Tested in desktop modeler.

fix: serialize empty text as empty string

---

packages/form-js-viewer/src/render/components/form-fields/Textarea.js

fix: textarea resizing behavior improvements

---

package-lock.json
packages/form-js-editor/assets/index.scss
packages/form-js-editor/package.json
packages/form-js-editor/rollup.config.js
packages/form-js-editor/src/features/dragging/Dragging.js
packages/form-js-editor/src/render/components/FormEditor.js

This uses an updated `dragula` version to make the `direction` dynamic. It detects whether the drop would happen inside a row or not and change the direction accordingly.
This makes drag & drop quite a bit smoother as it uses the correct axis depending where the cursor is located. Beforehand it would always have used the y-axis. 
Depends on https://github.com/bpmn-io/dragula/pull/1
Demo: https://demo-improve-dragging--camunda-form-playground.netlify.app/

Integrate `@bpmn-io/draggle`

---

packages/form-js-editor/src/features/properties-panel/entries/LabelEntry.js

Related to https://github.com/camunda/web-modeler/issues/5483
Same change as [`85937c4` (#728)](https://github.com/bpmn-io/form-js/pull/728/commits/85937c410f83bd023acd1a1c1a50018c18344f0a), but for labels

fix: serialize empty labels as empty string

---

packages/form-js-editor/assets/form-js-editor-base.css

I think it doesn't make sense to show during dragging. Let me know what you think.
We can also introduce another flag for dragging mode, but as we already set this one, I thought that would be enough.

style: do not show empty state while dragging

---

package-lock.json
package.json
packages/form-js-editor/assets/index.scss
packages/form-js-editor/package.json
packages/form-js-editor/rollup.config.js
packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/features/properties-panel/helper/index.js
packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/components/PlaygroundRoot.js

Depends on https://github.com/bpmn-io/properties-panel/pull/280
Related to https://github.com/camunda/team-hto/issues/344
Required by https://github.com/camunda/form-playground/pull/101
This allows to provide a feel popup container via config.
```js
new FormPlayground({
data,
schema,
propertiesPanel: {
feelPopupContainer: rootRef.current
},
});
```
Demo: https://feel-popup-root--camunda-form-playground.netlify.app/

Allow defining FEEL Popup container

---

package-lock.json
package.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/index.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanelModule.spec.js

Related to https://github.com/bpmn-io/properties-panel/pull/287
```js
const feelPopup = formEditor.get('feelPopup');
console.log('is open', feelPopup.isOpen());
feelPopup.close();
feelPopup.open(someElement, { type: 'feel' }, elementToRestoreFocusAfterClose);
```

Bump properties panel version

---

e2e/test-fixtures.js
package-lock.json
package.json
packages/form-js-viewer/test/helper/index.js
packages/form-js-viewer/test/spec/render/components/Description.spec.js

Related to https://github.com/camunda/team-hto/issues/360
Add `wcag21a` and `wcag21aa` rule sets to our a11y test setup.
Context: https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md#wcag-21-level-a--aa-rules

WCAG 2.1 AA rule sets

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/features/expression-language/ConditionChecker.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/condition-errors.json

Closes #825
I actually wonder whether this worked beforehand, as conditions never refer to form field IDs, but their respective key.
Seems like we had a lack of test coverage over here. Feel free to check @Skaiir!

fix(viewer): clean up errors for hidden fields

---

packages/form-js-editor/src/features/properties-panel/entries/InputKeyValuesSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ValuesExpressionEntry.js

Closes #305
There's a mild styling issue which are going to be fixed via https://github.com/bpmn-io/properties-panel/pull/300/commits, but since we're eventually going to bump the properties panel and the visuals aren't that big a deal, I feel like it's not worth monkey patching or syncing. If you think we should still wait lmk.

fix: move dynamic options hint to tooltip

---

packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/parts/SkipLink.js
packages/form-js-viewer/test/spec/render/components/form-fields/Taglist.spec.js

This is to provide a skip link to quickly navigate to the search via keyboard. This becomes useful once you have a lot of tags selected and want to quickly navigate to the search bar.
In general, skip links are a widely used pattern to skip parts of the content, only accessible for keyboard users and screenreaders.
Cf. https://webaim.org/techniques/skipnav/#hidden
Closes #435

feat(taglist): add skip to search

---

packages/form-js-editor/README.md
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-viewer/README.md

Closes #839
Added documentation of the editor events. Still quite simple for now, we can judge if we need to get into more detail later.
Also adjusted the viewer events to put the format individually, as I noticed the next event we need for form-fields doesn't match the usual format.

chore: document editor events

---

packages/form-js-editor/assets/form-js-editor-base.css

Closes #848
Closes #539
Improved the alignment of palette elements when scrollbar is visible, changed the focus to an outline instead of a margin to prevent blinking. Gave elements a small outline to make them pop. Made hover state also an outline. Compressed the palette a tiny bit.

fix: palette style improvements

---

packages/form-js-viewer/src/util/index.js

We accidently broke the types when merging `master` to `develop`

chore(getSchemaVariables): fixup JS docs

---

packages/form-js-editor/src/features/modeling/behavior/ValuesSourceBehavior.js
packages/form-js-editor/src/features/modeling/behavior/index.js
packages/form-js-editor/src/features/properties-panel/entries/ValuesSourceSelectEntry.js
packages/form-js-editor/test/spec/defaultValues.json
packages/form-js-editor/test/spec/features/modeling/behavior/ValuesSourceBehavior.spec.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

Closes #859
* Moves the values source clean-ups to a proper modeling behavior so it's also used when using API only
* Clean up `defaultValue` in case non-static values source is set

fix(editor): add values source modeling behavior

---

packages/form-js-editor/src/render/components/FormEditor.js

Related to https://github.com/camunda/team-hto/issues/387

fix(context-pad): add title to remove button

---

packages/form-js-editor/assets/form-js-editor-base.css

Related to https://github.com/camunda/team-hto/issues/384
I had to increase the placeholder text color a bit as it still reported less contrast in Axe.

style: improve placeholder color ratio

---

packages/form-js-editor/src/features/palette/components/Palette.js
packages/form-js-viewer/src/render/components/form-fields/Group.js
packages/form-js-viewer/test/spec/render/components/form-fields/Group.spec.js

Introducing the Containers group as this will become more relevant with the next to-be-added components (`dynamiclist`, `iFrame`).

feat(editor): introduce `container` group

---

packages/form-js-viewer/src/render/index.js

This helps extensions to use our hooks as well, especially helpers like `useSingleLineTemplateEvaluation` to offer FEEL support.

chore(viewer): export hooks

---

packages/form-js-viewer/assets/form-js-base.css

Closes #869
Nice improvement, I decided to go with the same colors as groups, just to not overextend our palette too much.

fix: give tables rendered by text some simple styling

---

packages/form-js-carbon-styles/src/carbon-styles.scss
packages/form-js-carbon-styles/test/spec/carbon-styles.spec.js
packages/form-js-carbon-styles/test/spec/complex.json

feat: Add Carbon compatibility styles

---

packages/form-js-editor/src/FormEditor.js
packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/index.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/hooks/useFlushDebounce.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/render/components/helper/mocks/index.js

feat: Implement form-js viewer debounce

---

package-lock.json
packages/form-js-viewer/package.json
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
packages/form-js-viewer/src/render/components/util/optionsUtil.js
packages/form-js-viewer/src/render/components/util/sanitizerUtil.js
packages/form-js-viewer/src/render/hooks/useCleanupMultiSelectValues.js
packages/form-js-viewer/src/render/hooks/useCleanupSingleSelectValue.js
packages/form-js-viewer/src/render/hooks/useGetLabelCorrelation.js
packages/form-js-viewer/test/spec/render/components/form-fields/Checklist.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/Radio.spec.js
packages/form-js-viewer/test/spec/render/components/form-fields/util/optionsUtil.spec.js

fix: properly handle all formats of options sources

---

packages/form-js-viewer/src/render/components/form-fields/Number.js

fix: revert debounce functionality on number fields

---

package-lock.json
packages/form-js-viewer/package.json

Hi,
With recent release, the demo.bpmn.io website build started to fail due to problems with dependencies of the form viewer:
```
<s> [webpack.Progress] 100% 
assets by status 7.26 MiB [cached] 70 assets
orphan modules 6.97 MiB [orphan] 1038 modules
runtime modules 13.7 KiB 48 modules
cacheable modules 12.7 MiB (javascript) 452 KiB (asset)
modules by path ./node_modules/cmmn-js/ 919 KiB (javascript) 81.8 KiB (asset) 165 modules
modules by path ./client/ 10.5 MiB (javascript) 56.8 KiB (asset) 18 modules
modules by path ./node_modules/bpmn-js-cli/ 20.7 KiB 16 modules
modules by path ./node_modules/dmn-js/dist/assets/ 153 KiB (javascript) 62.1 KiB (asset) 12 modules
modules by path ./node_modules/bpmn-js/dist/assets/ 82.6 KiB (javascript) 252 KiB (asset) 8 modules
modules by path …
```

fix: explicitly depend on lodash

---

packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/components/JSONEditor.js
packages/form-js-playground/src/components/autocompletion/index.js
packages/form-js-playground/src/index.js
packages/form-js-playground/test/custom/editor.js
packages/form-js-playground/test/custom/viewer.js
packages/form-js-playground/test/spec/Playground.spec.js

Partial PR
Related to https://github.com/bpmn-io/form-js/issues/918

Use named exports in playground

---

packages/form-js-editor/src/features/render-injection/slot-fill/SlotFillRoot.js
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/src/render/hooks/useDebounce.js
packages/form-js-editor/src/render/hooks/usePrevious.js
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js
packages/form-js-viewer/src/render/Renderer.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js
packages/form-js-viewer/src/render/hooks/useCleanupMultiSelectValues.js
packages/form-js-viewer/src/render/hooks/useDeepCompareState.js
packages/form-js-viewer/src/render/hooks/useFlushDebounce.js
packages/form-js-viewer/src/render/hooks/usePrevious.js
packages/form-js-viewer/test/helper/preactDebuggers.js

Related to https://github.com/camunda/team-hto/issues/444
This is only the first part of the changes. There's one big misuse left but it's super core and might take a bit for me to diagnose completely. But I've reduced down the warnings from 35ish to 1 which is progress.
I've still got another part of this on a local branch which is to merge the properties panel render tree with that of the rest of the editor, but still need a little bit of debugging for that one. Won't be long though. But let's merge as we go along.

chore: fix preact usages across application

---

packages/form-js-viewer/assets/form-js-base.css

fix: explicitely align table entries to center

---

packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/src/render/components/FormEditor.js

Closes #965
@volodymyr-melnykc I made the hiding threshold 100pixels instead because it still seems to look okay, let me know how it seems to you. 
@vsgoulart Opted for a mutationobserver for simplicity, since this is purely a visual thing

fix: improve text prompts of empty group components

---

.github/workflows/UPDATE_VISUAL_SNAPSHOTS.yml
.github/workflows/VISUAL_REGRESSION.yml

I don't believe the auto-update of screenshots is working out, it just makes us ignore the visual regression CI run on PRs and if we there's problems when we merge master to develop or vice-versa it updates the baseline screenshots wrongly like in [here](https://github.com/bpmn-io/form-js/commit/648c5d1e3d49952111a13958330c5095905b70b5) (and this is not the first time I noticed an update that shouldn't happen)
We have the instructions on how to update the screenshots [here](https://github.com/bpmn-io/form-js/blob/develop/e2e/README.md), it takes less than 5 min to update so I believe it's not a blocker

ci: Prevent auto-update of visual regression screenshots

---

packages/form-js-editor/assets/form-js-editor-base.css
packages/form-js-editor/src/features/properties-panel/PropertiesProvider.js
packages/form-js-editor/src/features/properties-panel/groups/SecurityAttributesGroup.js
packages/form-js-editor/src/features/properties-panel/groups/index.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/features/properties-panel/groups/SecurityAttributesGroup.spec.js
packages/form-js-viewer/src/render/components/form-fields/IFrame.js
packages/form-js-viewer/src/render/hooks/index.js
packages/form-js-viewer/src/render/hooks/useSecurityAttributesMap.js
packages/form-js-viewer/src/util/constants/IFrameConstants.js
packages/form-js-viewer/src/util/constants/index.js
packages/form-js-viewer/test/spec/iframes.json
packages/form-js-viewer/test/spec/render/components/form-fields/IFrame.spec.js
packages/form-json-schema/src/defs/component.json
packages/form-json-schema/src/defs/security.json
packages/form-json-schema/test/fixtures/iframe.js

feat: add security properties for iFrame

---

packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/util/numberFieldUtil.js
packages/form-js-viewer/src/render/hooks/index.js
packages/form-js-viewer/test/spec/render/components/form-fields/Number.spec.js

Closes #958
(again)
After a lot of reworks and problems I finally got this sorted.
For testing, make sure the debouncing is working, cleaning up when tabbing out. This should debounce when holding up or down arrow, when typing, and when clicking the arrows via the mouse. 
I've also as part of this removed some problem things, like the fact that we were still sending an onChange with 'NaN' (a concept we had removed, but not fully, via https://github.com/bpmn-io/form-js/issues/894), the test case is respectively changed. 
What we are keeping is the NaN state when pasting something that's not a valid number, this is only visual and is here to give users feedback, otherwise they might think pasting just doesn't do anything. In the future a toast element might be more appropriate. Anyways this …

feat: implement number field debouncing

---

packages/form-js-playground/rollup.config.js
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-viewer/src/render/components/form-fields/Table.js

With the table component we added the concept of adding demo data to the new component, this data was being added when importing forms into the modeler.
This PR prevents this from happening and only adds the demo data when the schema matches with the demo data
Closes #997

fix: Prevent demo data from being created on edited tables

---

packages/form-js-viewer/src/render/components/form-fields/Textarea.js

Closes #1011
We need to also recalculate the text-area size on input changes so that it doesn't wait for deboucing to kick in. 
This implementation ends up making the call twice (once on typing, once when the value change actually happens through debouncing), but we need to keep the value change one active so that the textarea still resizes when externals change its state.
Well it's only running twice if you type on character every 301ms. It's better to say it runs one extra time
Differentiating a self-triggered value change from an external one does not seem worth the effort. So I think this is the right fix.

fix: resize textarea on input changes

---

package-lock.json
package.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/Util.js
packages/form-js-editor/src/features/properties-panel/entries/ColumnEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ColumnsEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ColumnsExpressionEntry.js
packages/form-js-editor/src/features/properties-panel/entries/CustomValueEntry.js
packages/form-js-editor/src/features/properties-panel/entries/DefaultValueEntry.js
packages/form-js-editor/src/features/properties-panel/entries/HeightEntry.js
packages/form-js-editor/src/features/properties-panel/entries/HtmlEntry.js
packages/form-js-editor/src/features/properties-panel/entries/IFrameUrlEntry.js
packages/form-js-editor/src/features/properties-panel/entries/IdEntry.js
packages/form-js-editor/src/features/properties-panel/entries/InputKeyOptionsSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/KeyEntry.js
packages/form-js-editor/src/features/properties-panel/entries/NumberEntries.js
packages/form-js-editor/src/features/properties-panel/entries/PathEntry.js
packages/form-js-editor/src/features/properties-panel/entries/RowCountEntry.js
packages/form-js-editor/src/features/properties-panel/entries/StaticOptionsSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/TableDataSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ValueEntry.js
packages/form-js-editor/src/features/properties-panel/entries/factories/simpleRangeIntegerEntryFactory.js
packages/form-js-editor/src/features/properties-panel/groups/CustomPropertiesGroup.js

@Skaiir Please test it manually too in case I broke anything in the properties panel validations
The `useCallback`s are necessary because of [this](https://github.com/bpmn-io/properties-panel/commit/e93e986573d32adc361c64a1bc53cf1e38454715)

chore: bump properties-panel@3.18.0

---

packages/form-js-editor/src/features/properties-panel/entries/HeightEntry.js
packages/form-js-editor/src/features/properties-panel/entries/IFrameHeightEntry.js

Closes #956
Small change, but basically we don't automatically set the default value again every time we clear this field, as this used to feel really clumsy when wanting to change to a specific value.

fix: validate instead of automatically resetting height entries

---

package-lock.json
packages/form-js-viewer/src/render/components/Description.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/src/render/components/Label.js
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Datetime.js
packages/form-js-viewer/src/render/components/form-fields/IFrame.js
packages/form-js-viewer/src/render/components/form-fields/Number.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Select.js
packages/form-js-viewer/src/render/components/form-fields/Table.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/Textarea.js
packages/form-js-viewer/src/render/components/form-fields/Textfield.js
packages/form-js-viewer/src/render/components/form-fields/parts/Datepicker.js
packages/form-js-viewer/src/render/components/form-fields/parts/Timepicker.js

Fix a whole bunch of elements so they announce themselves properly in a screenreader.
* Include all description blocks in `aria-describedby`.
* Add `required` property to inputs that can be required.
* Add `aria-invalid` property to input which have validation errors.
* Do not announce the asterisk/star which denotes a required field.
* Have components generate their own error ID.
* Remove confusing use of `id` in Label. It now has an `id` and an `htmlFor` prop.
* Update groups `aria-labelledby` to point to an actual label.
Closes #1042 

feat(a11y): fields announce their descriptions and labels properly

---

packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js

fix: ensure repeatRenderManager passes down props correctly

---

packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/dynamic-list-variables.json

Closes #1085
Issue was that restProps also had "value" passed from outer elements, but it was the value of the full dynamic list. So it was overriding the value obtained in the map. Simply changed the variable name to get around the override. Added a test scenario to ensure this never happens again.

fix: properly pass `this` variable context to dynamic list elems

---

packages/form-js-editor/src/features/palette/index.js
packages/form-js-editor/test/spec/features/palette/PaletteModule.spec.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanelModule.spec.js
packages/form-js-playground/src/Playground.js
packages/form-js-playground/src/components/PlaygroundRoot.js
packages/form-js/test/spec/FormPlayground.spec.js

Sub-pr of https://github.com/bpmn-io/form-js/pull/1074

Sub-PR: expression fields fix playground root

---

packages/form-js-editor/src/features/properties-panel/Util.js
packages/form-js-editor/src/features/properties-panel/entries/KeyEntry.js
packages/form-js-editor/src/features/properties-panel/entries/PathEntry.js

fix: prevent prototype polution through keys and paths

---

packages/form-js-viewer/src/render/components/form-fields/Datetime.js
packages/form-js-viewer/src/render/components/util/dateTimeUtil.js

Closes #1099
The root cause issue for this is the fact that the datetime component has a lot of funky synchronization code that leads to onChange being called when it initializes. The simplest and quickest way to fix this, is to not call onChange when newValue = oldValue, and it makes sense generally. 
But ideally, we wouldn't want this logic branch to be called on init at all. Now I'm not sure I can fix this without a full refactor of datetime, and this component is a house of cards so my suggestion is, we take the easy fix for now, and I've raised [this issue](https://github.com/bpmn-io/form-js/issues/1120) to provide a refactor to the component in the future.

fix: prevent datetime from validating early

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/core/FormFieldInstanceRegistry.js
packages/form-js-viewer/src/core/index.js
packages/form-js-viewer/src/features/expressionLanguage/ConditionChecker.js
packages/form-js-viewer/src/render/components/FormField.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/core/FormFieldInstanceRegistry.spec.js

feat: implement formFieldInstanceRegistry

---

packages/form-js-viewer/src/Form.js
packages/form-js-viewer/src/features/expressionField/ExpressionLoopPreventer.js
packages/form-js-viewer/src/features/expressionField/index.js
packages/form-js-viewer/src/features/index.js
packages/form-js-viewer/src/render/components/form-fields/ExpressionField.js
packages/form-js-viewer/test/spec/Form.spec.js
packages/form-js-viewer/test/spec/chain-expressions.json
packages/form-js-viewer/test/spec/cyclical-expressions.json
packages/form-js-viewer/test/spec/render/components/form-fields/ExpressionField.spec.js
packages/form-js-viewer/test/spec/render/components/helper/mocks/index.js

fix: prevent expressions from recomputing more than once 

---

.gitignore
package-lock.json
package.json
packages/form-js-viewer-core/package.json
packages/form-js-viewer-render/RenderPlayground.jsx
packages/form-js-viewer-render/index.html
packages/form-js-viewer-render/jsconfig.json
packages/form-js-viewer-render/package.json
packages/form-js-viewer-render/src/index.js
packages/form-js-viewer-render/src/jsconfig.json
packages/form-js-viewer-render/test/.eslintrc
packages/form-js-viewer-render/test/index.spec.js
packages/form-js-viewer-render/test/jsconfig.json
packages/form-js-viewer-render/vite.config.js

v2: bootstrap viewer render project

---

packages/form-js-viewer/src/render/components/form-fields/Button.js
packages/form-js-viewer/test/spec/render/components/form-fields/Button.spec.js

fix: button labels properly evaluate expressions

---

packages/form-js-viewer/src/core/FieldFactory.js

chore: ensure group paths are properly registered on add

---

packages/form-js-editor/src/features/properties-panel/PropertiesPanel.js
packages/form-js-editor/src/features/properties-panel/PropertiesPanelHeaderProvider.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanelHeaderProvider.spec.js
packages/form-js-playground/test/spec/Playground.spec.js

Related to https://github.com/camunda/team-hto/issues/630

feat: enable passing of documentation link to form properties panel

---

package-lock.json
package.json
packages/form-js-editor/package.json
packages/form-js-editor/src/features/properties-panel/entries/StaticColumnsSourceEntry.js
packages/form-js-editor/src/features/properties-panel/entries/StaticOptionsSourceEntry.js
packages/form-js-editor/src/features/properties-panel/groups/CustomPropertiesGroup.js
packages/form-json-schema/test/fixtures/package-lock.json

Closes #1200
See https://github.com/bpmn-io/properties-panel/commit/bb1cfb05a41f3e7632ace7f34927e198e43ad775 if you want to look into why this was done. But basically, list autoSorting was deemed an antifeature. It is completely gone from the properties panel and only throws a log warning. This PR clears those warnings.

chore: removed deprecated `shouldSort` properties panel attributes

---

packages/form-js-editor/src/features/dragging/Dragging.js

Closes https://github.com/bpmn-io/form-js/issues/1218

fix: Prevent drag and drop from accessing prop when undefined

---

packages/form-js-editor/src/features/dragging/Dragging.js
packages/form-js-editor/test/spec/FormEditor.spec.js

fix: disallow drop when no associated field is found

---

packages/form-js-editor/src/features/properties-panel/Util.js
packages/form-js-editor/src/features/properties-panel/entries/AcceptEntry.js
packages/form-js-editor/src/features/properties-panel/entries/DefaultValueEntry.js
packages/form-js-editor/src/features/properties-panel/entries/DescriptionEntry.js
packages/form-js-editor/src/features/properties-panel/entries/MultipleEntry.js
packages/form-js-editor/src/features/properties-panel/entries/index.js
packages/form-js-editor/src/features/properties-panel/groups/GeneralGroup.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/features/properties-panel/groups/GeneralGroup.spec.js
packages/form-js-editor/test/spec/form.json
packages/form-json-schema/src/defs/component.json
packages/form-json-schema/src/defs/rules/rules-allowed-properties.json

feat: add filepicker properties panel

---

packages/form-js-editor/src/features/properties-panel/entries/VersionTagEntry.js
packages/form-js-editor/src/features/properties-panel/entries/index.js
packages/form-js-editor/src/features/properties-panel/groups/GeneralGroup.js
packages/form-js-editor/test/spec/features/properties-panel/groups/GeneralGroup.spec.js
packages/form-json-schema/src/index.json

Related to https://github.com/camunda/camunda-modeler/issues/4463

feat: add version tag support

---

packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/features/repeatRender/RepeatRenderManager.js
packages/form-js-viewer/test/spec/Form.spec.js

fix: dynamic list collapsing issue

---

packages/form-js-viewer/src/render/components/form-fields/Table.js
packages/form-js-viewer/test/spec/render/components/form-fields/Table.spec.js

Closes #1139
Decided to simply go for JSON serialization here. It's the most permissive approach and also is the easiest to understand where you went wrong (if at all). This changes how arrays are rendered, but the previous way was simply concatenating the contents without spaces which was definitely not "defined behavior", so we don't need to worry about any backwards compatibility issues.
I've considered circular references, they are not a problem as in any case we do a JSON serialization of the entire data during import, which would crash in case of circular object references. Whether we should have something to handle circular references in source data, debatable, but another issue entirely.

fix: serialize object table cells using the JSON serializer

---

packages/form-js-editor/README.md
packages/form-js-playground/README.md
packages/form-js-viewer/README.md
packages/form-js/README.md

Closes #1175
READMEs should be pretty much independently readable so I added sample data and schemas everywhere so that there's no questions. Also added `type:default` that is an actual requirement for the forms, fixing the source issue.

chore: cleaned up usage examples in READMEs across repo

---

e2e/carbon/carbon.scss
e2e/carbon/index.html
e2e/carbon/theme.scss
e2e/theming/index.html
e2e/theming/theme.scss
e2e/visual/theming.spec.js
packages/form-js-carbon-styles/src/carbon-styles.scss
packages/form-js-carbon-styles/test/spec/carbon-styles.spec.js
packages/form-js-carbon-styles/test/spec/theme.scss
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/test/spec/Form.spec.js

The arrows in the select were broken because we removed the `.cds--g10` theme classes.
I also fixed an issue with a token that doesn't exist

fix: fix carbonization

---

packages/form-js-carbon-styles/src/carbon-styles.js
packages/form-js-carbon-styles/src/carbon-styles.scss
packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/render/components/form-fields/Checkbox.js
packages/form-js-viewer/src/render/components/form-fields/Checklist.js
packages/form-js-viewer/src/render/components/form-fields/Radio.js
packages/form-js-viewer/src/render/components/form-fields/Taglist.js
packages/form-js-viewer/src/render/components/form-fields/parts/SearchableSelect.js
packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js

Related to https://github.com/bpmn-io/form-js/pull/1140
Closes https://github.com/camunda/camunda/issues/19945

fix(styles): Don't clip radio buttons

---

packages/form-js-viewer/src/render/components/form-fields/FilePicker.js

Closes https://github.com/camunda/camunda-modeler/issues/4644

fix: prevent form editor from breaking on invalid expression on filepicker prop

---

package-lock.json
package.json
packages/form-js-editor/src/FormEditor.js
packages/form-js-editor/src/features/keyboard/FormEditorKeyboardBindings.js
packages/form-js-editor/src/render/Renderer.js
packages/form-js-editor/src/render/components/FormEditor.js
packages/form-js-editor/test/spec/FormEditor.spec.js
packages/form-js-viewer/test/spec/Form.spec.js

This updates the library to diagram-js@15 which ships breaking changes.
BREAKING CHANGES:
* Keyboard is now implicitly bound to the container element.
Calls to `keyboard.bind` with `node` and `keyboard.bindTo`
now result with a descriptive console error and have no effect.
Related to https://github.com/bpmn-io/diagram-js/pull/662

Add implicit keyboard binding / migrate to diagram-js@15

---

packages/form-js-carbon-styles/src/carbon-styles.scss
packages/form-js-editor/src/features/properties-panel/PropertiesProvider.js
packages/form-js-editor/src/features/properties-panel/entries/DocumentsDataSource.js
packages/form-js-editor/src/features/properties-panel/entries/EndpointKey.js
packages/form-js-editor/src/features/properties-panel/entries/MaxHeightEntry.js
packages/form-js-editor/src/features/properties-panel/groups/DownloadSettings.js
packages/form-js-editor/src/features/properties-panel/groups/GeneralGroup.js
packages/form-js-editor/src/features/properties-panel/groups/index.js
packages/form-js-editor/src/render/components/editor-form-fields/EditorDocumentPreview.js
packages/form-js-editor/src/render/components/editor-form-fields/index.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js
packages/form-js-editor/test/spec/form.json
packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-playground/test/spec/form.json
packages/form-js-viewer/assets/form-js-base.css
packages/form-js-viewer/src/render/components/Errors.js
packages/form-js-viewer/src/render/components/form-fields/DocumentPreview.js
packages/form-js-viewer/src/render/components/form-fields/icons/Download.svg
packages/form-js-viewer/test/spec/render/components/form-fields/DocumentPreview.spec.js

Add runtime implementation of the document preview component and missing design fixes
Closes #1327

feat: add runtime implementation of document preview component

---

packages/form-js-viewer/src/render/components/form-fields/Table.js
packages/form-js-viewer/test/spec/render/components/form-fields/DocumentPreview.spec.js

This filters out invalid data from the table component which would make it break the entire editor if it happened.
Closes #1337

fix: prevent table component from breaking with invalid data

---

packages/form-js-playground/test/spec/Playground.spec.js
packages/form-js-viewer/src/render/components/form-fields/DocumentPreview.js

This PR adds the content hash injection into the document preview URL so it works with Camunda Tasklist.
This is a temporary fix and we should try to remove it as soon as we can for the reasons explained here: https://github.com/bpmn-io/form-js/issues/1341
Closes #1340

feat: Inject content hash into document preview URL

---

.github/workflows/DEPLOY_PLAYGROUND_PREVIEW.yml
packages/form-js-playground/src/components/autocompletion/index.js
packages/form-js-playground/test/spec/JSONEditor.spec.js

This PR fixes the autocompletion on the form input, before we were just completing the variable names which resulted in invalid JSON.
Closes https://github.com/camunda/camunda-modeler/issues/4758

fix: form input autocomplete

---

packages/form-js-editor/src/features/properties-panel/entries/StaticOptionsSourceEntry.js
packages/form-js-editor/test/spec/features/properties-panel/PropertiesPanel.spec.js

Before we were not deleting the default value of a radio group when we deleted the static option. This PR fixes this.
Closes #1351

fix: reset default value when statid option is deleted

---

.github/workflows/CI.yml
packages/form-js-viewer/src/render/components/form-fields/Textfield.js

This fixes an issue when a form is instantiated inside a shadow DOM node together with React. When typing inside a textfield the value would disappear after a while (after the debounce function runs)
I couldn't dig 100% to the root reason of this, but I believe this is due to the differences in the event management between shadow DOM together with the React/Preact event handling
This fix was suggested by customers on this [support ticket](https://jira.camunda.com/browse/SUPPORT-26988)
Closes #1399

fix: explictly pass textfield change event target

---

packages/form-js-viewer/src/render/components/form-fields/Table.js
packages/form-js-viewer/test/spec/render/components/form-fields/Table.spec.js

Prevent falsy values (except `null` and `undefined`) from being rendered in table elements
Closes #1383

fix: handle falsy values on table serialization

---

packages/form-js-editor/src/features/properties-panel/entries/RepeatableEntry.js

Closes #1398
This increases the limit of dynamic list items by default to 100. It's high enough that it should handle most reasonable requests, but low enough that it won't cause any meltdowns of the editor when someone enters an absurd value into the properties panel. Any further and we need pagination IMO.

chore: bump the dynamic list default number of items to 100

---

packages/form-js-editor/src/features/properties-panel/entries/DisabledEntry.js
packages/form-js-editor/src/features/properties-panel/entries/ReadonlyEntry.js

Related to #1401
Might be closing if  volodymyr agrees to drop the first req: `The "Read only" option should be placed before the "Disabled" option in the properties panel.`

chore: adjust the readonly and disabled tooltips
